# generated by datamodel-codegen:
#   filename:  02_api_spec.yaml
#   timestamp: 2025-12-01T13:29:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SignalRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    timeframe: Optional[str] = None


class SignalResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    allowed: Optional[bool] = None
    reason: Optional[str] = None


class RiskCheckRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    risk_usd: float = Field(
        ..., description='Maximum risk in USD allowed for this trade'
    )
    sl_distance_usd: float = Field(
        ..., description='Distance to stop loss in USD (per unit/contract)'
    )
    min_lot: float = Field(..., description='Minimum allowed lot size (e.g., 0.01)')


class RiskCheckResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_execute: Optional[bool] = None
    lot: Optional[float] = None
    reason: Optional[str] = None


class Token(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    access_token: Optional[str] = None
    token_type: Optional[str] = None


class User(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    username: Optional[str] = None
    email: Optional[str] = None
    is_active: Optional[bool] = None


class Fund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None


class FundCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: Optional[str] = None


class Strategy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    type: Optional[str] = None
    config_json: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class StrategyCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    fund_id: UUID
    type: str
    config_json: Dict[str, Any]


class Direction(Enum):
    long = 'LONG'
    short = 'SHORT'


class GameLevel(Enum):
    a_game = 'A_GAME'
    b_game = 'B_GAME'
    c_game = 'C_GAME'


class MentalState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    greed_level: Optional[int] = None
    fear_level: Optional[int] = None
    tilt_level: Optional[int] = None
    confidence_level: Optional[int] = None
    discipline_level: Optional[int] = None


class TimelineEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[str] = None
    description: Optional[str] = None
    order_index: Optional[int] = None


class RootCause(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    problem: Optional[str] = None
    why_exist: Optional[str] = None
    flaw: Optional[str] = None
    correction: Optional[str] = None
    logic: Optional[str] = None


class JournalEntryCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    direction: Direction
    session: Optional[str] = None
    entry_price: Optional[float] = None
    exit_price: Optional[float] = None
    pnl_amount: Optional[float] = None
    pnl_r: Optional[float] = None
    risk_amount: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    context_score: Optional[int] = Field(None, ge=1, le=10)
    game_level: Optional[GameLevel] = None
    mental_state: Optional[MentalState] = None
    timeline_events: Optional[List[TimelineEvent]] = None
    root_cause: Optional[RootCause] = None


class JournalEntryResponse(JournalEntryCreate):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None
