# generated by datamodel-codegen:
#   filename:  04_api_spec.yaml
#   timestamp: 2026-03-03T20:45:38+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AlphaRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    formula: str = Field(..., examples=['rank(close / delay(close, 5))'])
    symbol: str = Field(..., examples=['XAU_USD'])
    timeframe: Optional[str] = Field(None, examples=['H1'])
    start_date: Optional[AwareDatetime] = None
    end_date: Optional[AwareDatetime] = None


class AlphaResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    signal: Optional[List[float]] = None
    metrics: Optional[Dict[str, Any]] = None
    timestamps: Optional[List[AwareDatetime]] = None


class MarketAnalysisRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    trend_4h: Optional[str] = None
    current_price: Optional[float] = None
    key_levels: Optional[List[float]] = None
    recent_signals: Optional[List[Dict[str, Any]]] = None
    image_b64: Optional[str] = None


class JournalAnalysisRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    entry_content: str
    entry_id: Optional[UUID] = None
    user_id: UUID


class Status(Enum):
    ingestion_started = 'INGESTION_STARTED'
    pending = 'PENDING'
    ingested = 'INGESTED'
    failed = 'FAILED'


class Data(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filename: Optional[str] = None
    collection: Optional[str] = None
    status: Optional[Status] = None
    message: Optional[str] = None


class Data1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filename: Optional[str] = None
    title: Optional[str] = None
    author: Optional[str] = None
    status: Optional[Status] = None
    total_chunks: Optional[int] = None
    last_ingested_at: Optional[AwareDatetime] = None


class Datum(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    filename: Optional[str] = None
    title: Optional[str] = None
    author: Optional[str] = None
    status: Optional[Status] = None
    last_ingested_at: Optional[AwareDatetime] = None
    chunks_queued: Optional[int] = None


class ExternalSearchRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    query: str
    limit: Optional[int] = 5
    partner_id: Optional[str] = None


class LibraryHit(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: Optional[str] = None
    score: Optional[float] = None
    source: Optional[str] = None
    entry_content: Optional[str] = None
    entry_id: Optional[UUID] = None
    user_id: Optional[str] = None


class SMCNarrativeRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    smc_data: Optional[Dict[str, Any]] = None
    price_context: Optional[Dict[str, Any]] = None


class AnalysisResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    insight: Optional[str] = None
    timestamp: Optional[AwareDatetime] = None


class Status3(Enum):
    open = 'OPEN'
    closed = 'CLOSED'
    rejected = 'REJECTED'


class Direction(Enum):
    long = 'LONG'
    short = 'SHORT'


class Trade(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    trade_id: UUID
    strategy_run_id: Optional[UUID] = None
    broker_account_id: Optional[UUID] = None
    symbol: str
    strategy_name: str
    signal_timestamp: AwareDatetime
    status: Status3
    rejection_reason: Optional[str] = None
    direction: Direction
    entry_price: float
    sl_price: float
    tp_price: float
    lot_size: float
    risk_usd: float
    atr_pips: Optional[float] = None
    rr_ratio: Optional[float] = None
    pnl_usd: Optional[float] = None
    mae_usd: Optional[float] = None
    mfe_usd: Optional[float] = None
    exit_price: Optional[float] = None
    exit_timestamp: Optional[AwareDatetime] = None
    metadata_json: Optional[Dict[str, Any]] = None


class ResponseStatus(Enum):
    success = 'success'
    error = 'error'
    fail = 'fail'


class ErrorCode(Enum):
    auth_1001 = 'AUTH_1001'
    auth_1002 = 'AUTH_1002'
    auth_1003 = 'AUTH_1003'
    auth_1004 = 'AUTH_1004'
    auth_1005 = 'AUTH_1005'
    val_2001 = 'VAL_2001'
    val_2002 = 'VAL_2002'
    val_2003 = 'VAL_2003'
    val_2004 = 'VAL_2004'
    val_2005 = 'VAL_2005'
    val_2006 = 'VAL_2006'
    val_2007 = 'VAL_2007'
    res_3001 = 'RES_3001'
    res_3002 = 'RES_3002'
    res_3003 = 'RES_3003'
    biz_4001 = 'BIZ_4001'
    biz_4002 = 'BIZ_4002'
    biz_4003 = 'BIZ_4003'
    biz_4004 = 'BIZ_4004'
    rate_5001 = 'RATE_5001'
    rate_5002 = 'RATE_5002'
    srv_9001 = 'SRV_9001'
    srv_9002 = 'SRV_9002'
    srv_9003 = 'SRV_9003'
    srv_9004 = 'SRV_9004'


class DataSourceType(Enum):
    api = 'api'
    csv = 'csv'
    db = 'db'
    websocket = 'websocket'


class DataSourceProvider(Enum):
    oanda = 'OANDA'
    binance = 'BINANCE'


class DataSource(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: str
    provider: DataSourceProvider
    type: DataSourceType
    config_json: Dict[str, Any]
    is_active: Optional[bool] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class DataSourceCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    provider: DataSourceProvider
    type: DataSourceType
    config_json: Dict[str, Any]
    is_active: Optional[bool] = None


class DataSourceUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    provider: Optional[DataSourceProvider] = None
    type: Optional[DataSourceType] = None
    config_json: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class Meta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: Optional[int] = None
    per_page: Optional[int] = None
    total: Optional[int] = None
    total_pages: Optional[int] = None


class AuthTokens(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    access_token: str
    refresh_token: Optional[str] = None
    token_type: Optional[str] = 'Bearer'
    expires_in: int
    expires_at: AwareDatetime


class RateLimitInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    limit: int
    remaining: int
    reset: AwareDatetime
    reset_in_seconds: int


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field: Optional[str] = None
    message: str
    code: Optional[ErrorCode] = None


class Candle(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    time: AwareDatetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    is_complete: Optional[bool] = None


class Data2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: Optional[str] = Field(
        None, description='Markdown formatted briefing content'
    )
    timestamp: Optional[AwareDatetime] = None


class MonteCarloRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    trades: Optional[List[Dict[str, Any]]] = None
    iterations: Optional[int] = 1000


class SensitivityMetrics(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    p95: Optional[float] = None
    median: Optional[float] = None
    worst: Optional[float] = None
    best: Optional[float] = None


class Data3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    imported_count: Optional[int] = None
    skipped_count: Optional[int] = None
    errors: Optional[List[str]] = None


class Data4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    balance: Optional[float] = None
    currency: Optional[str] = None


class TradeStatus(Enum):
    open = 'OPEN'
    closed = 'CLOSED'
    rejected = 'REJECTED'


class TradeDirection(Enum):
    long = 'LONG'
    short = 'SHORT'


class TradeResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    trade_id: UUID
    symbol: str
    strategy_name: str
    signal_timestamp: AwareDatetime
    direction: TradeDirection
    entry_price: float
    sl_price: float
    tp_price: float
    lot_size: float
    risk_usd: float
    status: TradeStatus
    pnl_usd: Optional[float] = None
    exit_price: Optional[float] = None
    exit_timestamp: Optional[AwareDatetime] = None
    rejection_reason: Optional[str] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PaginatedResponseTradeResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[TradeResponse]
    message: Optional[str] = None
    meta: Meta
    timestamp: AwareDatetime
    rate_limit: Optional[RateLimitInfo] = None


class SignalRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    timeframe: Optional[str] = None


class RiskCheckRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    risk_usd: float = Field(
        ..., description='Maximum risk in USD allowed for this trade'
    )
    sl_distance_usd: float = Field(
        ..., description='Distance to stop loss in USD (per unit/contract)'
    )
    min_lot: float = Field(..., description='Minimum allowed lot size (e.g., 0.01)')


class RiskCheckResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_execute: Optional[bool] = None
    lot: Optional[float] = None
    reason: Optional[str] = None


class UserCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    username: str
    email: str
    password: str


class UserResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    username: Optional[str] = None
    email: Optional[str] = None
    is_active: Optional[bool] = None


class Direction1(Enum):
    bullish = 'BULLISH'
    bearish = 'BEARISH'


class SmartOrderRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    broker_account_id: UUID
    symbol: str
    direction: Direction1
    stop_loss: Optional[float] = None
    generated_by: str
    reason: Optional[str] = None
    risk_usd: Optional[float] = None
    confidence: Optional[float] = 1.0
    pain_threshold: Optional[float] = 10.0
    atr_multiplier: Optional[float] = 1.0


class OrderResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    instrument: Optional[str] = None
    units: Optional[str] = None
    price: Optional[str] = None
    time: Optional[str] = None


class BrokerAccountResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    broker_name: Optional[str] = None
    account_name: Optional[str] = None
    account_number: Optional[str] = None
    is_active: Optional[bool] = None
    is_live: Optional[bool] = None
    created_at: Optional[AwareDatetime] = None


class UserPreferencesResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    default_fund_id: Optional[UUID] = None
    preferred_timeframes: Optional[List[str]] = None
    default_symbol: Optional[str] = None
    session_preferences: Optional[List[str]] = None
    supported_symbols: Optional[List[str]] = None


class StrategyType(Enum):
    mtf_smc_basic = 'MTF_SMC_BASIC'
    long_short_equity = 'LONG_SHORT_EQUITY'
    macro_tactical = 'MACRO_TACTICAL'
    multi_asset = 'MULTI_ASSET'


class UpdatePreferencesDto(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    default_fund_id: Optional[UUID] = None
    strategy_type: Optional[StrategyType] = None
    asset_classes: Optional[List[str]] = None
    max_risk_per_trade: Optional[float] = None
    default_lot_size: Optional[float] = None
    max_drawdown_threshold: Optional[float] = None
    max_portfolio_beta: Optional[float] = None
    gross_exposure_limit: Optional[float] = None
    net_exposure_limit: Optional[float] = None
    position_limit_single: Optional[float] = None
    position_limit_sector: Optional[float] = None
    preferred_timeframes: Optional[List[str]] = None
    default_symbol: Optional[str] = None
    session_preferences: Optional[List[str]] = None


class Fund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None


class FundCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: str
    strategy_type: Optional[StrategyType] = None
    asset_classes: Optional[List[str]] = None
    max_risk_per_trade: Optional[float] = None
    default_lot_size: Optional[float] = None
    max_drawdown_threshold: Optional[float] = None
    max_portfolio_beta: Optional[float] = None
    gross_exposure_limit: Optional[float] = None
    net_exposure_limit: Optional[float] = None
    position_limit_single: Optional[float] = None
    position_limit_sector: Optional[float] = None


class FundUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    description: Optional[str] = None
    strategy_type: Optional[StrategyType] = None
    asset_classes: Optional[List[str]] = None
    max_risk_per_trade: Optional[float] = None
    default_lot_size: Optional[float] = None
    max_drawdown_threshold: Optional[float] = None
    max_portfolio_beta: Optional[float] = None
    gross_exposure_limit: Optional[float] = None
    net_exposure_limit: Optional[float] = None
    position_limit_single: Optional[float] = None
    position_limit_sector: Optional[float] = None


class StrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    template_id: Optional[str] = None
    broker_account_id: Optional[UUID] = None
    config_json: Optional[Dict[str, Any]] = None
    risk_settings: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class StrategyCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    fund_id: UUID
    template_id: str
    broker_account_id: UUID
    config_json: Dict[str, Any]
    risk_settings: Optional[Dict[str, Any]] = None


class StrategyConfigUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config_json: Optional[Dict[str, Any]] = None
    risk_settings: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class StrategyTemplate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    default_config: Optional[Dict[str, Any]] = None
    default_risk_settings: Optional[Dict[str, Any]] = None


class Direction2(Enum):
    long = 'LONG'
    short = 'SHORT'


class GameLevel(Enum):
    a_game = 'A_GAME'
    b_game = 'B_GAME'
    c_game = 'C_GAME'


class MentalState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    greed_level: Optional[int] = None
    fear_level: Optional[int] = None
    tilt_level: Optional[int] = None
    confidence_level: Optional[int] = None
    discipline_level: Optional[int] = None


class TimelineEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[str] = None
    description: Optional[str] = None
    order_index: Optional[int] = None


class RootCause(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    problem: Optional[str] = None
    why_exist: Optional[str] = None
    flaw: Optional[str] = None
    correction: Optional[str] = None
    logic: Optional[str] = None


class JournalEntryCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    direction: Direction2
    session: Optional[str] = None
    entry_price: Optional[float] = None
    exit_price: Optional[float] = None
    pnl_amount: Optional[float] = None
    pnl_r: Optional[float] = None
    risk_amount: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    context_score: Optional[int] = Field(None, ge=1, le=10)
    game_level: Optional[GameLevel] = None
    mental_state: Optional[MentalState] = None
    timeline_events: Optional[List[TimelineEvent]] = None
    root_cause: Optional[RootCause] = None


class JournalEntryResponse(JournalEntryCreate):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class BacktestRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strategy_id: UUID
    symbol: str
    timeframe: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    initial_capital: float


class Type(Enum):
    deposit = 'DEPOSIT'
    withdrawal = 'WITHDRAWAL'


class TransactionCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fund_id: UUID
    transaction_date: AwareDatetime
    type: Type
    amount: float
    currency: Optional[str] = 'USD'
    status: Optional[str] = None
    reference: Optional[str] = None
    description: Optional[str] = None
    payment_method: Optional[str] = None
    trading_account: Optional[str] = None


class TransactionResponse(TransactionCreate):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class MarketCategoryCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    order_index: Optional[int] = None


class MarketSymbol(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: UUID
    symbol: str
    display_name: Optional[str] = None
    category_id: UUID
    order_index: int
    details: Optional[Dict[str, Any]] = Field(None, description='Flexible JSON object')


class MarketSymbolCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    display_name: Optional[str] = None
    order_index: Optional[int] = None


class SignalBatchRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    broker: Optional[str] = Field(None, description='Broker name (e.g. OANDA)')
    symbols: Optional[List[str]] = Field(
        None, description='Optional list of symbols to override broker defaults'
    )


class Direction3(Enum):
    long = 'LONG'
    short = 'SHORT'
    neutral = 'NEUTRAL'


class SignalResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    timeframe: Optional[str] = None
    timestamp: Optional[AwareDatetime] = None
    direction: Optional[Direction3] = None
    entry_price: Optional[float] = None
    sl_price: Optional[float] = None
    tp_price: Optional[float] = None
    reason: Optional[str] = None
    broker: Optional[str] = None
    strategy_name: Optional[str] = None
    confidence: Optional[float] = 0.0
    sentiment_score: Optional[float] = Field(
        None, description='Market sentiment (-1.0 to 1.0)'
    )
    sentiment_reason: Optional[str] = None


class FoundryAssembleResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pipeline_hash: Optional[str] = None
    errors: Optional[List[str]] = None


class WalkForwardRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    timeframe: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    config: Dict[str, Any]


class WalkForwardResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    robustness_score: Optional[int] = None
    avg_sharpe_test: Optional[float] = None
    details: Optional[List[Dict[str, Any]]] = None


class StrategyBacktestRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str = Field(
        ..., description='Python code implementing strategy(data) -> entries, exits'
    )
    symbol: str
    timeframe: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    fees: Optional[float] = None
    slippage: Optional[float] = None


class SavedStrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None
    code: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None
    last_results: Optional[Dict[str, Any]] = None
    is_public: Optional[bool] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class SavedStrategyCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: Optional[str] = None
    code: str
    parameters: Optional[Dict[str, Any]] = None
    last_results: Optional[Dict[str, Any]] = None
    is_public: Optional[bool] = None


class SavedStrategyUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    description: Optional[str] = None
    code: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None
    last_results: Optional[Dict[str, Any]] = None
    is_public: Optional[bool] = None


class Status4(Enum):
    starting = 'STARTING'
    active = 'ACTIVE'
    stopped = 'STOPPED'
    error = 'ERROR'
    stopping = 'STOPPING'


class Deployment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    strategy_id: Optional[UUID] = None
    stock_symbol: Optional[str] = None
    timeframe: Optional[str] = None
    status: Optional[Status4] = None
    is_live: Optional[bool] = None
    config_snapshot: Optional[Dict[str, Any]] = None
    last_error: Optional[str] = None
    started_at: Optional[AwareDatetime] = None
    stopped_at: Optional[AwareDatetime] = None


class DeploymentCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strategy_id: UUID
    stock_symbol: str
    timeframe: str
    is_live: Optional[bool] = None
    config_snapshot: Dict[str, Any]


class ChatSession(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    strategy_id: Optional[UUID] = None
    title: Optional[str] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class Role(Enum):
    user = 'user'
    assistant = 'assistant'
    system = 'system'


class ChatMessage(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    session_id: Optional[UUID] = None
    role: Optional[Role] = None
    content: Optional[str] = None
    context_snapshot: Optional[Dict[str, Any]] = None
    created_at: Optional[AwareDatetime] = None


class ChatSessionCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strategy_id: Optional[UUID] = None
    initial_message: Optional[str] = Field(
        None, description='Optional initial message to start the session'
    )


class ChatMessageCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    content: str
    context_snapshot: Optional[Dict[str, Any]] = None


class Data5(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    report: Optional[str] = None
    timestamp: Optional[AwareDatetime] = None


class BrokerAccount(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    fund_id: Optional[UUID] = None
    broker_name: Optional[str] = None
    account_name: Optional[str] = None
    account_number: Optional[str] = None
    supported_symbols: Optional[List[str]] = None
    risk_settings: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None
    is_live: Optional[bool] = None


class BrokerAccountCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fund_id: UUID
    broker_name: str
    account_name: str
    account_number: Optional[str] = None
    credentials: Dict[str, Any]
    supported_symbols: Optional[List[str]] = None
    risk_settings: Optional[Dict[str, Any]] = None
    is_live: Optional[bool] = False


class BrokerAccountUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    account_name: Optional[str] = None
    account_number: Optional[str] = None
    credentials: Optional[Dict[str, Any]] = None
    supported_symbols: Optional[List[str]] = None
    risk_settings: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None
    is_live: Optional[bool] = None


class FoundryAssembleRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config: Optional[StrategyConfigUpdate] = None


class FoundryValidateRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config_id: UUID
    start_date: Optional[date] = None
    end_date: Optional[date] = None


class APIResponseFoundryValidateResponseData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    robustness_score: Optional[int] = None
    is_passed: Optional[bool] = None


class Allocation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strategy_id: Optional[UUID] = None
    weight: Optional[float] = None


class PortfolioAllocationUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    allocations: Optional[List[Allocation]] = None


class MentalHandHistoryCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    journal_entry_id: UUID
    pre_trade_emotion: str
    trigger_event: str
    irrational_thought: str
    behavioral_result: str
    correction_logic: str


class BacktestMetrics(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total_return: Optional[float] = None
    total_return_percent: Optional[float] = None
    max_drawdown: Optional[float] = None
    max_drawdown_percent: Optional[float] = None
    win_rate: Optional[float] = None
    benchmark_return: Optional[float] = None
    sharpe_ratio: Optional[float] = None
    sortino_ratio: Optional[float] = None
    alpha: Optional[float] = None
    beta: Optional[float] = None
    information_ratio: Optional[float] = None
    total_trades: Optional[int] = None
    winning_trades: Optional[int] = None
    losing_trades: Optional[int] = None


class SystemPromptCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: Optional[str] = None
    template: str
    input_variables: Optional[List[str]] = None
    is_active: Optional[bool] = True


class SystemPromptUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: Optional[str] = None
    template: Optional[str] = None
    input_variables: Optional[List[str]] = None
    is_active: Optional[bool] = None


class SystemPromptResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    owner_id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None
    template: Optional[str] = None
    input_variables: Optional[List[str]] = None
    version: Optional[int] = None
    is_active: Optional[bool] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class PluginResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    version: Optional[str] = None
    category: Optional[str] = None
    is_active: Optional[bool] = Field(
        None, description='True if active for current user'
    )


class PluginConfigUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config_overrides: Dict[str, Any]


class Type1(Enum):
    daily = 'DAILY'
    alerts = 'ALERTS'


class Briefing(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    content: Optional[str] = None
    generated_at: Optional[AwareDatetime] = None
    type: Optional[Type1] = None


class SMCRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str = Field(..., examples=['XAUUSD'])
    timeframe: Optional[str] = Field('H1', examples=['H1'])
    open: List[float]
    high: List[float]
    low: List[float]
    close: List[float]
    volume: Optional[List[float]] = None
    timestamps: Optional[List[str]] = None
    oi_call: Optional[List[float]] = None
    oi_put: Optional[List[float]] = None
    oi_strikes: Optional[List[float]] = None


class Type2(Enum):
    bullish = 'bullish'
    bearish = 'bearish'


class SMCOrderBlock(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type2] = None
    index: Optional[int] = None
    top: Optional[float] = None
    bottom: Optional[float] = None
    mitigated: Optional[bool] = None
    strength: Optional[str] = None


class SMCFVG(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type2] = None
    index: Optional[int] = None
    top: Optional[float] = None
    bottom: Optional[float] = None
    mitigated: Optional[bool] = None


class Type4(Enum):
    bullish_sweep = 'bullish_sweep'
    bearish_sweep = 'bearish_sweep'


class SMCSweep(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type4] = None
    index: Optional[int] = None
    level: Optional[float] = None
    description: Optional[str] = None


class SMCStructureLabel(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    index: Optional[int] = None
    text: Optional[str] = None
    price: Optional[float] = None


class Type5(Enum):
    buy_side = 'buy_side'
    sell_side = 'sell_side'


class Meta1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    wick_ratio: Optional[float] = None
    volume_ratio: Optional[float] = None
    rsi_value: Optional[float] = None


class SMCInducement(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type5] = None
    index: Optional[int] = None
    timestamp: Optional[AwareDatetime] = None
    price: Optional[float] = None
    level: Optional[float] = None
    meta: Optional[Meta1] = None


class SMCStructure(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pivots: Optional[List[Dict[str, Any]]] = None
    labels: Optional[List[SMCStructureLabel]] = None
    events: Optional[List[Dict[str, Any]]] = None
    inducements: Optional[List[SMCInducement]] = None


class SMCResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    order_blocks: Optional[List[SMCOrderBlock]] = None
    fvgs: Optional[List[SMCFVG]] = None
    liquidity_sweeps: Optional[List[SMCSweep]] = None
    inducement_signals: Optional[List[SMCInducement]] = None
    structure: Optional[SMCStructure] = None
    auto_fibs: Optional[Dict[str, float]] = None


class EmaRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: List[float]
    span: Optional[int] = 14


class RsiRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    close: List[float]
    window: Optional[int] = 14


class AtrRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    high: List[float]
    low: List[float]
    close: List[float]
    window: Optional[int] = 14


class MacdRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    close: List[float]
    fast: Optional[int] = 12
    slow: Optional[int] = 26
    signal: Optional[int] = 9


class AdxRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    high: List[float]
    low: List[float]
    close: List[float]
    length: Optional[int] = 14


class IndicatorResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    values: Optional[List[float]] = None


class MacdResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    macd: Optional[List[float]] = None
    signal: Optional[List[float]] = None
    hist: Optional[List[float]] = None


class AdxResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    adx: Optional[List[float]] = None
    dmp: Optional[List[float]] = None
    dmn: Optional[List[float]] = None


class OpportunityLog(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    timestamp: Optional[AwareDatetime] = None
    symbol: Optional[str] = None
    direction: Optional[str] = None
    filter_name: Optional[str] = None
    filter_value: Optional[float] = None
    threshold_value: Optional[float] = None
    reason: Optional[str] = None
    strategy_name: Optional[str] = None


class MarketSymbolResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    symbol: Optional[str] = None
    display_name: Optional[str] = None
    is_active: Optional[bool] = None
    data_source_id: Optional[UUID] = None
    details: Optional[Dict[str, Any]] = Field(
        None, description='Flexible JSON object for instrument specifics'
    )


class MarketSymbolUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    is_active: Optional[bool] = None
    details: Optional[Dict[str, Any]] = None


class StrategyChatRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: str
    user_id: str
    strategy_id: Optional[str] = None
    context_code: Optional[str] = None
    context_stats: Optional[Dict[str, Any]] = None
    image_b64: Optional[str] = None


class OpenInterestCommon(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    contract_symbol: Optional[str] = None
    dte: Optional[int] = None
    strike: Optional[float] = None
    call_oi: Optional[float] = None
    put_oi: Optional[float] = None


class AnalysisSummary(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total_call_oi: Optional[float] = None
    total_put_oi: Optional[float] = None
    pcr: Optional[float] = None
    max_call_strike: Optional[float] = None
    max_put_strike: Optional[float] = None
    oiwap: Optional[float] = None


class AnalysisDistribution(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strike: Optional[float] = None
    call_oi: Optional[float] = None
    put_oi: Optional[float] = None
    net_delta: Optional[float] = None


class OpenInterestAnalysisResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    summary: Optional[AnalysisSummary] = None
    distribution: Optional[List[AnalysisDistribution]] = None


class DriftAnalysis(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pcr_drift: Optional[float] = None
    net_oi_drift: Optional[float] = None
    call_wall_shift: Optional[float] = None
    put_wall_shift: Optional[float] = None
    oiwap_shift: Optional[float] = None
    sentiment: Optional[str] = None


class UnifiedOIProfileResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    snapshot_at: Optional[AwareDatetime] = None
    prev_snapshot_at: Optional[AwareDatetime] = None
    price: Optional[float] = None
    gamma_regime: Optional[str] = None
    crowding_regime: Optional[str] = None
    sentiment_drift: Optional[DriftAnalysis] = None
    gamma_levels: Optional[List[Dict[str, Any]]] = None
    summary: Optional[AnalysisSummary] = None


class Status5(Enum):
    active = 'active'
    inactive = 'inactive'
    busy = 'busy'


class Agent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    name: Optional[str] = None
    role: Optional[str] = None
    description: Optional[str] = None
    status: Optional[Status5] = None
    capabilities: Optional[List[str]] = None


class TelegramUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    update_id: Optional[int] = None
    message: Optional[Dict[str, Any]] = None


class LinkTelegramRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    chat_id: int


class LinkTelegramResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    success: Optional[bool] = None
    message: Optional[str] = None
    chat_id: Optional[int] = None


class TelegramStatusResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    linked: Optional[bool] = None
    chat_id: Optional[int] = None
    linked_at: Optional[AwareDatetime] = None
    bot_configured: Optional[bool] = None


class SendTelegramMessageRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: str


class ConfigureBotRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    bot_token: str


class ConfigureBotResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    success: Optional[bool] = None
    message: Optional[str] = None
    bot_username: Optional[str] = None


class APIResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[Dict[str, Any]] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseStrategyTemplateList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[StrategyTemplate]] = None


class APIResponseDataSource(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[DataSource] = None


class APIResponseRiskCheckResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[RiskCheckResponse] = None


class APIResponseUserResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[UserResponse] = None


class APIResponseUserPreferencesResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[UserPreferencesResponse] = None


class APIResponseBriefingResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data2] = None


class APIResponseSuccess(RootModel[APIResponse]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: APIResponse


class APIResponseFund(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Fund] = None


class APIResponseStrategyResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[StrategyResponse] = None


class APIResponseJournalEntryResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[JournalEntryResponse] = None


class MonteCarloResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    iterations: Optional[int] = None
    max_drawdown: Optional[SensitivityMetrics] = None
    total_return: Optional[SensitivityMetrics] = None


class APIResponseTransactionResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[TransactionResponse] = None


class APIResponseTransactionImportResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data3] = None


class APIResponseBalanceResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data4] = None


class PaginatedResponseTransactionResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[TransactionResponse]
    message: Optional[str] = None
    meta: Meta
    timestamp: AwareDatetime


class PaginatedResponseFund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[Fund]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseStrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[StrategyResponse]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseJournalEntryResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[JournalEntryResponse]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class BacktestResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    status: Optional[str] = None
    metrics: Optional[BacktestMetrics] = None
    trades: Optional[List[Dict[str, Any]]] = None
    plot_json: Optional[str] = Field(None, description='Serialized Plotly JSON string')


class MarketCategory(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: UUID
    name: str
    order_index: int
    items: List[MarketSymbol]


class APIResponseSignalList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[SignalResponse]] = None


class APIResponseSignalResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[SignalResponse] = None


class APIResponseSymbolList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[str]] = None


class APIResponseDeploymentList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[Deployment]] = None


class APIResponseDeployment(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Deployment] = None


class APIResponseChatSessionList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[ChatSession]] = None


class APIResponseChatSession(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[ChatSession] = None


class APIResponseChatMessageList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[ChatMessage]] = None


class APIResponseChatMessage(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[ChatMessage] = None


class APIResponseAIReport(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data5] = None


class APIResponseBrokerAccount(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[BrokerAccount] = None


class APIResponseBrokerAccountList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[BrokerAccount]] = None


class APIResponseFoundryAssembleResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[FoundryAssembleResponse] = None


class APIResponseFoundryValidateResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[APIResponseFoundryValidateResponseData] = None


class APIResponseStrategyList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[Dict[str, Any]]] = None


class APIResponseBriefing(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Briefing] = None


class APIResponseWalkForwardResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[WalkForwardResponse] = None


class APIResponseOpenInterestAnalytics(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[OpenInterestAnalysisResponse] = None


class APIResponseUnifiedOIProfile(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[UnifiedOIProfileResponse] = None


class APIResponseAgent(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Agent] = None


class APIResponseAgentList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[Agent]] = None


class APIResponseAlpha(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[AlphaResponse] = None


class APIResponseIngestionResult(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data] = None


class APIResponseLibraryStatus(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[Data1] = None


class APIResponseLibraryBookList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[Datum]] = None


class APIResponseLibraryResults(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[LibraryHit]] = None


class APIResponseAnalysis(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[AnalysisResponse] = None


class APIResponseTradeList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[Trade]] = None


class APIResponseDataSourceList(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[List[DataSource]] = None


class APIResponseBacktestResponse(APIResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Optional[BacktestResponse] = None
