# generated by datamodel-codegen:
#   filename:  02_api_spec.yaml
#   timestamp: 2025-12-04T13:10:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ResponseStatus(Enum):
    success = 'success'
    error = 'error'
    fail = 'fail'


class ErrorCode(Enum):
    auth_1001 = 'AUTH_1001'
    auth_1002 = 'AUTH_1002'
    auth_1003 = 'AUTH_1003'
    auth_1004 = 'AUTH_1004'
    auth_1005 = 'AUTH_1005'
    val_2001 = 'VAL_2001'
    val_2002 = 'VAL_2002'
    val_2003 = 'VAL_2003'
    val_2004 = 'VAL_2004'
    val_2005 = 'VAL_2005'
    val_2006 = 'VAL_2006'
    val_2007 = 'VAL_2007'
    res_3001 = 'RES_3001'
    res_3002 = 'RES_3002'
    res_3003 = 'RES_3003'
    biz_4001 = 'BIZ_4001'
    biz_4002 = 'BIZ_4002'
    biz_4003 = 'BIZ_4003'
    biz_4004 = 'BIZ_4004'
    rate_5001 = 'RATE_5001'
    rate_5002 = 'RATE_5002'
    srv_9001 = 'SRV_9001'
    srv_9002 = 'SRV_9002'
    srv_9003 = 'SRV_9003'
    srv_9004 = 'SRV_9004'


class Meta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    page: Optional[int] = None
    per_page: Optional[int] = None
    total: Optional[int] = None
    total_pages: Optional[int] = None


class AuthTokens(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    access_token: str
    refresh_token: Optional[str] = None
    token_type: Optional[str] = 'Bearer'
    expires_in: int
    expires_at: AwareDatetime


class RateLimitInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    limit: int
    remaining: int
    reset: AwareDatetime
    reset_in_seconds: int


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field: Optional[str] = None
    message: str
    code: Optional[ErrorCode] = None


class Data(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    imported_count: Optional[int] = None
    skipped_count: Optional[int] = None
    errors: Optional[List[str]] = None


class APIResponseTransactionImportResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[Data] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class Data1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    balance: Optional[float] = None
    currency: Optional[str] = None


class APIResponseBalanceResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[Data1] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class SignalRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    timeframe: Optional[str] = None


class Direction(Enum):
    long = 'LONG'
    short = 'SHORT'


class SignalResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[str] = None
    timeframe: Optional[str] = None
    timestamp: Optional[AwareDatetime] = None
    direction: Optional[Direction] = None
    entry_price: Optional[float] = None
    sl_price: Optional[float] = None
    tp_price: Optional[float] = None
    reason: Optional[str] = None


class RiskCheckRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    risk_usd: float = Field(
        ..., description='Maximum risk in USD allowed for this trade'
    )
    sl_distance_usd: float = Field(
        ..., description='Distance to stop loss in USD (per unit/contract)'
    )
    min_lot: float = Field(..., description='Minimum allowed lot size (e.g., 0.01)')


class RiskCheckResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    can_execute: Optional[bool] = None
    lot: Optional[float] = None
    reason: Optional[str] = None


class UserCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    username: str
    email: str
    password: str


class UserResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    username: Optional[str] = None
    email: Optional[str] = None
    is_active: Optional[bool] = None


class Fund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    description: Optional[str] = None


class FundCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: Optional[str] = None


class StrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    name: Optional[str] = None
    type: Optional[str] = None
    config_json: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class StrategyCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    fund_id: UUID
    type: str
    config_json: Dict[str, Any]


class GameLevel(Enum):
    a_game = 'A_GAME'
    b_game = 'B_GAME'
    c_game = 'C_GAME'


class MentalState(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    greed_level: Optional[int] = None
    fear_level: Optional[int] = None
    tilt_level: Optional[int] = None
    confidence_level: Optional[int] = None
    discipline_level: Optional[int] = None


class TimelineEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[str] = None
    description: Optional[str] = None
    order_index: Optional[int] = None


class RootCause(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    problem: Optional[str] = None
    why_exist: Optional[str] = None
    flaw: Optional[str] = None
    correction: Optional[str] = None
    logic: Optional[str] = None


class JournalEntryCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    direction: Direction
    session: Optional[str] = None
    entry_price: Optional[float] = None
    exit_price: Optional[float] = None
    pnl_amount: Optional[float] = None
    pnl_r: Optional[float] = None
    risk_amount: Optional[float] = None
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    context_score: Optional[int] = Field(None, ge=1, le=10)
    game_level: Optional[GameLevel] = None
    mental_state: Optional[MentalState] = None
    timeline_events: Optional[List[TimelineEvent]] = None
    root_cause: Optional[RootCause] = None


class JournalEntryResponse(JournalEntryCreate):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class BacktestRequest(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    strategy_id: UUID
    symbol: str
    timeframe: str
    start_date: AwareDatetime
    end_date: AwareDatetime
    initial_capital: float


class BacktestResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[str] = None
    status: Optional[str] = None
    metrics: Optional[Dict[str, Any]] = None
    trades: Optional[List[Dict[str, Any]]] = None


class Type(Enum):
    deposit = 'DEPOSIT'
    withdrawal = 'WITHDRAWAL'


class TransactionCreate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fund_id: UUID
    transaction_date: AwareDatetime
    type: Type
    amount: float
    currency: Optional[str] = 'USD'
    status: Optional[str] = None
    reference: Optional[str] = None
    description: Optional[str] = None
    payment_method: Optional[str] = None
    trading_account: Optional[str] = None


class TransactionResponse(TransactionCreate):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[UUID] = None
    created_at: Optional[AwareDatetime] = None
    updated_at: Optional[AwareDatetime] = None


class APIResponseSignalResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[SignalResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseRiskCheckResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[RiskCheckResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseUserResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[UserResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseFund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[Fund] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseStrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[StrategyResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseJournalEntryResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[JournalEntryResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseBacktestResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[BacktestResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class APIResponseTransactionResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: Optional[TransactionResponse] = None
    message: Optional[str] = None
    errors: Optional[List[ErrorDetail]] = None
    meta: Optional[Meta] = None
    auth: Optional[AuthTokens] = None
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseTransactionResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[TransactionResponse]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseFund(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[Fund]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseStrategyResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[StrategyResponse]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime


class PaginatedResponseJournalEntryResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: ResponseStatus
    data: List[JournalEntryResponse]
    message: Optional[str] = None
    meta: Meta
    rate_limit: Optional[RateLimitInfo] = None
    timestamp: AwareDatetime
