"""refactor_risk_and_symbols

Revision ID: 07fc82dbba14
Revises: a9742bb393fb
Create Date: 2025-12-30 06:35:11.440312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07fc82dbba14'
down_revision: Union[str, Sequence[str], None] = 'a9742bb393fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('supported_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('broker_accounts', sa.Column('risk_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('funds', sa.Column('strategy_type', sa.Enum('MTF_SMC_BASIC', 'LONG_SHORT_EQUITY', 'MACRO_TACTICAL', 'MULTI_ASSET', name='strategy_type_enum'), nullable=False))
    op.add_column('funds', sa.Column('asset_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('funds', sa.Column('max_risk_per_trade', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('funds', sa.Column('default_lot_size', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('funds', sa.Column('max_drawdown_threshold', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('funds', sa.Column('max_portfolio_beta', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('funds', sa.Column('gross_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('funds', sa.Column('net_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('funds', sa.Column('position_limit_single', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('funds', sa.Column('position_limit_sector', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_column('user_preferences', 'position_limit_single')
    op.drop_column('user_preferences', 'max_portfolio_beta')
    op.drop_column('user_preferences', 'strategy_type')
    op.drop_column('user_preferences', 'asset_classes')
    op.drop_column('user_preferences', 'default_lot_size')
    op.drop_column('user_preferences', 'supported_symbols')
    op.drop_column('user_preferences', 'max_drawdown_threshold')
    op.drop_column('user_preferences', 'max_risk_per_trade')
    op.drop_column('user_preferences', 'position_limit_sector')
    op.drop_column('user_preferences', 'gross_exposure_limit')
    op.drop_column('user_preferences', 'net_exposure_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('net_exposure_limit', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='In percentage'))
    op.add_column('user_preferences', sa.Column('gross_exposure_limit', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='In percentage'))
    op.add_column('user_preferences', sa.Column('position_limit_sector', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Max % per sector'))
    op.add_column('user_preferences', sa.Column('max_risk_per_trade', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('max_drawdown_threshold', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('supported_symbols', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='List of supported symbols for multi-asset strategies'))
    op.add_column('user_preferences', sa.Column('default_lot_size', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('asset_classes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Supported asset classes: EQUITY, FX, COMMODITIES, FIXED_INCOME'))
    op.add_column('user_preferences', sa.Column('strategy_type', postgresql.ENUM('MTF_SMC_BASIC', 'LONG_SHORT_EQUITY', 'MACRO_TACTICAL', 'MULTI_ASSET', name='strategytype'), autoincrement=False, nullable=False, comment='Strategy type: basic MTF/SMC to advanced multi-asset'))
    op.add_column('user_preferences', sa.Column('max_portfolio_beta', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('position_limit_single', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Max % per single position'))
    op.drop_column('funds', 'position_limit_sector')
    op.drop_column('funds', 'position_limit_single')
    op.drop_column('funds', 'net_exposure_limit')
    op.drop_column('funds', 'gross_exposure_limit')
    op.drop_column('funds', 'max_portfolio_beta')
    op.drop_column('funds', 'max_drawdown_threshold')
    op.drop_column('funds', 'default_lot_size')
    op.drop_column('funds', 'max_risk_per_trade')
    op.drop_column('funds', 'asset_classes')
    op.drop_column('funds', 'strategy_type')
    op.drop_column('broker_accounts', 'risk_settings')
    op.drop_column('broker_accounts', 'supported_symbols')
    # ### end Alembic commands ###
