"""Add broker_account_id and template_id

Revision ID: 1b9650e6e1b1
Revises: f3f7ff98c665
Create Date: 2025-12-23 01:12:06.425252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b9650e6e1b1'
down_revision: Union[str, Sequence[str], None] = 'f3f7ff98c665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('broker_account_id', sa.UUID(), nullable=True))
    op.add_column('strategies', sa.Column('template_id', sa.String(), nullable=False, comment="Identifier for the strategy logic template (e.g., 'SMC_V1')"))
    op.add_column('strategies', sa.Column('risk_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Instance-specific risk configuration'))
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_comment='Strategy-specific configuration parameters',
               existing_nullable=False)
    op.create_foreign_key(None, 'strategies', 'broker_accounts', ['broker_account_id'], ['id'])
    op.drop_column('strategies', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Strategy class/type identifier'))
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy-specific configuration parameters',
               existing_comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_nullable=False)
    op.drop_column('strategies', 'risk_settings')
    op.drop_column('strategies', 'template_id')
    op.drop_column('strategies', 'broker_account_id')
    # ### end Alembic commands ###
