"""Add open_interest table

Revision ID: 1c634932f29f
Revises: 5fe7ded1a020
Create Date: 2026-01-04 19:12:38.588863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c634932f29f'
down_revision: Union[str, Sequence[str], None] = '5fe7ded1a020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_interest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('contract_symbol', sa.String(length=50), nullable=False),
    sa.Column('dte', sa.Integer(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('call_oi', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('put_oi', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_symbol', 'strike', 'snapshot_at', name='uq_open_interest_contract_strike_snapshot')
    )
    op.create_index('ix_open_interest_contract_symbol', 'open_interest', ['contract_symbol'], unique=False)
    op.create_index('ix_open_interest_snapshot_at', 'open_interest', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_open_interest_snapshot_at', table_name='open_interest')
    op.drop_index('ix_open_interest_contract_symbol', table_name='open_interest')
    op.drop_table('open_interest')
    # ### end Alembic commands ###
