"""fix chat session fk

Revision ID: 1d50cf6d651a
Revises: 1ef7bd3e98ae
Create Date: 2025-12-28 02:18:27.737180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d50cf6d651a'
down_revision: Union[str, Sequence[str], None] = '1ef7bd3e98ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_sessions_strategy_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'saved_strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_strategy_id_fkey', 'chat_sessions', 'strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###
