"""Restore updated_at to candles

Revision ID: 1f67da7009e5
Revises: 4c4512d24b9e
Create Date: 2025-12-09 16:16:50.447448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f67da7009e5'
down_revision: Union[str, Sequence[str], None] = '4c4512d24b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record last update timestamp'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles', 'updated_at')
    # ### end Alembic commands ###
