"""add updated_at to strategies

Revision ID: 2217d0a14157
Revises: 1b9650e6e1b1
Create Date: 2025-12-24 13:19:15.085019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2217d0a14157'
down_revision: Union[str, Sequence[str], None] = '1b9650e6e1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_accounts', 'credentials_encrypted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_trades_broker_account_id'), 'trades', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_run_id'), 'trades', ['strategy_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_strategy_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_broker_account_id'), table_name='trades')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.alter_column('broker_accounts', 'credentials_encrypted',
               existing_type=sa.String(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
