"""Add UserPreferences

Revision ID: 23f81f9a3e7f
Revises: c449a6e4c0e0
Create Date: 2025-12-04 18:53:56.896068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23f81f9a3e7f'
down_revision: Union[str, Sequence[str], None] = 'c449a6e4c0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_fund_id', sa.UUID(), nullable=True),
    sa.Column('strategy_type', sa.Enum('MTF_SMC_BASIC', 'LONG_SHORT_EQUITY', 'MACRO_TACTICAL', 'MULTI_ASSET', name='strategytype'), nullable=False, comment='Strategy type: basic MTF/SMC to advanced multi-asset'),
    sa.Column('asset_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Supported asset classes: EQUITY, FX, COMMODITIES, FIXED_INCOME'),
    sa.Column('max_risk_per_trade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_lot_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_drawdown_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_portfolio_beta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gross_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True, comment='In percentage'),
    sa.Column('net_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True, comment='In percentage'),
    sa.Column('position_limit_single', sa.Numeric(precision=5, scale=2), nullable=True, comment='Max % per single position'),
    sa.Column('position_limit_sector', sa.Numeric(precision=5, scale=2), nullable=True, comment='Max % per sector'),
    sa.Column('preferred_timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Preferred trading timeframes'),
    sa.Column('default_symbol', sa.String(length=20), nullable=False),
    sa.Column('session_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Trading session preferences: LONDON, NY, ASIA'),
    sa.Column('supported_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of supported symbols for multi-asset strategies'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
