"""Add system_configs table

Revision ID: 24660acd5860
Revises: 266e46a0de70
Create Date: 2026-01-14 02:49:35.959528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24660acd5860'
down_revision: Union[str, Sequence[str], None] = '266e46a0de70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment="Config key (e.g. 'supported_timeframes')"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Config value (JSON)'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.drop_table('alembic_version_pipeline')
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.drop_constraint('market_categories_name_key', 'market_categories', type_='unique')
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint('market_categories_name_key', 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.create_table('alembic_version_pipeline',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pipeline_pkc')
    )
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
