"""add risk_percentage to funds

Revision ID: 266e46a0de70
Revises: 4b9c6dd54fc7
Create Date: 2026-01-10 11:51:52.956248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266e46a0de70'
down_revision: Union[str, Sequence[str], None] = '4b9c6dd54fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('risk_percentage', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'risk_percentage')
    # ### end Alembic commands ###
