"""Add library_books table

Revision ID: 2d8e2a8e29d3
Revises: 8e17d8f517c8
Create Date: 2026-02-28 11:15:16.898123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8e2a8e29d3'
down_revision: Union[str, Sequence[str], None] = '8e17d8f517c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'INGESTED', 'FAILED', name='ingestionstatus'), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_telegram_chat_mappings_user_id'), 'telegram_chat_mappings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_chat_mappings_user_id'), table_name='telegram_chat_mappings')
    op.drop_table('library_books')
    # ### end Alembic commands ###
