"""Align models with spec

Revision ID: 31e6113eead6
Revises: b26d5044f048
Create Date: 2026-01-01 02:41:05.754480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31e6113eead6'
down_revision: Union[str, Sequence[str], None] = 'b26d5044f048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_accounts', 'credentials_encrypted',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('user', 'assistant', 'system', name='chat_role_enum'),
               existing_nullable=False)
    op.alter_column('deployments', 'config_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('deployments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               nullable=False)
    op.alter_column('signal_logs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('signal_logs', 'meta_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('strategies', 'broker_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategies', 'broker_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('signal_logs', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('signal_logs', 'confidence',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('deployments', 'status',
               existing_type=sa.Enum('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deployments', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', 'system', name='chat_role_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('broker_accounts', 'credentials_encrypted',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
