"""Add data_source to candles

Revision ID: 37554e1cfa53
Revises: a729b4d32520
Create Date: 2025-12-22 18:14:12.861730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37554e1cfa53'
down_revision: Union[str, Sequence[str], None] = 'a729b4d32520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('data_source', sa.String(length=50), server_default='OANDA', nullable=False, comment='Source of data (e.g. OANDA, BINANCE)'))
    op.drop_index('ix_candles_symbol_timeframe_timestamp', table_name='candles')
    op.create_index(op.f('ix_candles_data_source'), 'candles', ['data_source'], unique=False)
    op.create_index('ix_candles_symbol_timeframe_timestamp_source', 'candles', ['symbol', 'timeframe', 'timestamp', 'data_source'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles_symbol_timeframe_timestamp_source', table_name='candles')
    op.drop_index(op.f('ix_candles_data_source'), table_name='candles')
    op.create_index('ix_candles_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.drop_column('candles', 'data_source')
    # ### end Alembic commands ###
