"""add_trade_id_to_journal

Revision ID: 408ad73b5547
Revises: 2a32a3d3a932
Create Date: 2025-12-19 12:42:10.122878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408ad73b5547'
down_revision: Union[str, Sequence[str], None] = '2a32a3d3a932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('trade_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_journal_entries_trade_id'), 'journal_entries', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_trade_id'), table_name='journal_entries')
    op.drop_column('journal_entries', 'trade_id')
    # ### end Alembic commands ###
