"""Add type and schema_json to DataSource

Revision ID: 4c4512d24b9e
Revises: c2e453cfec25
Create Date: 2025-12-09 13:55:48.233050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c4512d24b9e'
down_revision: Union[str, Sequence[str], None] = 'c2e453cfec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.alter_column('candles', 'timeframe',
               existing_type=sa.VARCHAR(length=10),
               comment='Timeframe identifier (15m, 1h, 4h, D)',
               existing_nullable=False)
    op.alter_column('candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Candle open timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('candles', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Opening price',
               existing_nullable=False)
    op.alter_column('candles', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Highest price',
               existing_nullable=False)
    op.alter_column('candles', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Lowest price',
               existing_nullable=False)
    op.alter_column('candles', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Closing price',
               existing_nullable=False)
    op.alter_column('candles', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Trading volume',
               existing_nullable=False)
    op.alter_column('candles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               comment='Whether the candle is closed/complete',
               existing_nullable=True)
    op.alter_column('candles', 'ema_9_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(9) on 4H timeframe (for 15m candles, aligned)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(200) on 4H timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_d',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(200) on Daily timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'atr_14_15m',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='ATR(14) on 15m timeframe (for stop loss calculation)',
               existing_nullable=True)
    op.alter_column('candles', 'body_to_wick_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Body-to-Wick Ratio (Rv) for vector candle confirmation',
               existing_nullable=True)
    op.alter_column('candles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_table_comment(
        'candles',
        'OHLCV candlestick data with multi-timeframe indicators',
        existing_comment=None,
        schema=None
    )
    op.drop_column('candles', 'updated_at')
    op.add_column('data_sources', sa.Column('type', sa.String(), nullable=False, comment='Type of data source (e.g., api, csv, db)'))
    op.add_column('data_sources', sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected data schema (e.g., column names for CSV, API response structure)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'schema_json')
    op.drop_column('data_sources', 'type')
    op.add_column('candles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'candles',
        existing_comment='OHLCV candlestick data with multi-timeframe indicators',
        schema=None
    )
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.alter_column('candles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('candles', 'body_to_wick_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Body-to-Wick Ratio (Rv) for vector candle confirmation',
               existing_nullable=True)
    op.alter_column('candles', 'atr_14_15m',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='ATR(14) on 15m timeframe (for stop loss calculation)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_d',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(200) on Daily timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(200) on 4H timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_9_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(9) on 4H timeframe (for 15m candles, aligned)',
               existing_nullable=True)
    op.alter_column('candles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the candle is closed/complete',
               existing_nullable=True)
    op.alter_column('candles', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Trading volume',
               existing_nullable=False)
    op.alter_column('candles', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Closing price',
               existing_nullable=False)
    op.alter_column('candles', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Lowest price',
               existing_nullable=False)
    op.alter_column('candles', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Highest price',
               existing_nullable=False)
    op.alter_column('candles', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Opening price',
               existing_nullable=False)
    op.alter_column('candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Candle open timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('candles', 'timeframe',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Timeframe identifier (15m, 1h, 4h, D)',
               existing_nullable=False)
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    # ### end Alembic commands ###
