"""Add OpportunityLog table

Revision ID: 57f4a5ab916b
Revises: 7fe3421ff035
Create Date: 2026-01-03 13:10:39.513805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f4a5ab916b'
down_revision: Union[str, Sequence[str], None] = '7fe3421ff035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
