"""Add is_active to market_symbols

Revision ID: 5fe7ded1a020
Revises: e09819f1be5d
Create Date: 2026-01-04 12:49:23.727215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe7ded1a020'
down_revision: Union[str, Sequence[str], None] = 'e09819f1be5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_symbols', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_symbols', 'is_active')
    # ### end Alembic commands ###
