"""Add provider to data_sources

Revision ID: 617e8fa4eb75
Revises: 57f4a5ab916b
Create Date: 2026-01-04 00:04:49.161532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617e8fa4eb75'
down_revision: Union[str, Sequence[str], None] = '57f4a5ab916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('provider', sa.String(), nullable=True, comment='Provider Implementation (e.g., OANDA, BINANCE)'))
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='User-defined alias',
               existing_comment='Provider name (e.g., OANDA, BINANCE)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='Provider name (e.g., OANDA, BINANCE)',
               existing_comment='User-defined alias',
               existing_nullable=False)
    op.drop_column('data_sources', 'provider')
    # ### end Alembic commands ###
