"""consolidate_schema_and_fix_drifts

Revision ID: 6772ce98e149
Revises: 32966e01de9c
Create Date: 2026-03-03 01:43:59.836441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6772ce98e149'
down_revision: Union[str, Sequence[str], None] = '32966e01de9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'INGESTED', 'FAILED', name='ingestionstatus'), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('strategy_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('essential_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_execution_logs_deployment_id'), 'strategy_execution_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_logs_timestamp'), 'strategy_execution_logs', ['timestamp'], unique=False)
    op.drop_index('ix_news_articles_external_id', table_name='news_articles')
    op.drop_index('ix_news_articles_id', table_name='news_articles')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_index('ix_news_articles_symbol', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_economic_events_datetime', table_name='economic_events')
    op.drop_index('ix_economic_events_external_id', table_name='economic_events')
    op.drop_index('ix_economic_events_id', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_table('alembic_version_pipeline')
    op.drop_index('ix_cot_records_report_date', table_name='cot_records')
    op.drop_index('ix_cot_records_symbol', table_name='cot_records')
    op.drop_table('cot_records')
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('broker_accounts', 'platform')
    op.add_column('candles', sa.Column('symbol', sa.String(length=20), nullable=True, comment='Denormalized symbol for easier querying (e.g. XAUUSD)'))
    
    # Data migration for existing candles
    op.execute("""
        UPDATE candles 
        SET symbol = ms.symbol 
        FROM market_symbols ms 
        WHERE candles.market_symbol_id = ms.id
    """)
    
    # Now set to NOT NULL
    op.alter_column('candles', 'symbol', nullable=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index('ix_candles_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='User-defined alias',
               existing_comment='Provider name (e.g., OANDA, BINANCE)',
               existing_nullable=False)
    op.alter_column('data_sources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment='Provider Implementation (e.g., OANDA, BINANCE)',
               existing_nullable=True)
    op.alter_column('funds', 'risk_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.drop_column('funds', 'updated_at')
    op.drop_column('funds', 'initial_balance')
    op.drop_constraint('market_categories_name_key', 'market_categories', type_='unique')
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    op.drop_constraint('mental_states_journal_entry_id_fkey', 'mental_states', type_='foreignkey')
    op.create_foreign_key(None, 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.add_column('open_interest', sa.Column('snapshot_at', sa.DateTime(), nullable=False))
    op.add_column('open_interest', sa.Column('contract_symbol', sa.String(length=50), nullable=False))
    op.add_column('open_interest', sa.Column('dte', sa.Integer(), nullable=False))
    op.add_column('open_interest', sa.Column('strike', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('open_interest', sa.Column('call_oi', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('open_interest', sa.Column('put_oi', sa.Numeric(precision=18, scale=2), nullable=True))
    # Drop default before casting to avoid DatatypeMismatch
    op.execute('ALTER TABLE open_interest ALTER COLUMN id DROP DEFAULT')
    op.alter_column('open_interest', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::text::uuid')
    op.drop_index('idx_oi_symbol', table_name='open_interest')
    op.drop_index('idx_oi_timestamp', table_name='open_interest')
    op.create_index('ix_open_interest_contract_symbol', 'open_interest', ['contract_symbol'], unique=False)
    op.create_index('ix_open_interest_dte', 'open_interest', ['dte'], unique=False)
    op.create_index('ix_open_interest_snapshot_at', 'open_interest', ['snapshot_at'], unique=False)
    op.create_index('ix_open_interest_snapshot_at_symbol', 'open_interest', ['snapshot_at', 'contract_symbol'], unique=False)
    op.create_unique_constraint('uq_open_interest_contract_strike_snapshot', 'open_interest', ['contract_symbol', 'strike', 'snapshot_at'])
    op.drop_column('open_interest', 'symbol')
    op.drop_column('open_interest', 'change_in_oi')
    op.drop_column('open_interest', 'volume')
    op.drop_column('open_interest', 'timestamp')
    op.drop_column('open_interest', 'open_interest')
    op.drop_constraint('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sentiment_scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               comment='Sentiment score (-1.0 to 1.0)',
               existing_nullable=False)
    op.alter_column('sentiment_scores', 'source_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sentiment source contributions',
               existing_nullable=True)
    op.drop_index('ix_sentiment_scores_id', table_name='sentiment_scores')
    op.create_index(op.f('ix_sentiment_scores_created_at'), 'sentiment_scores', ['created_at'], unique=False)
    op.add_column('signal_logs', sa.Column('strategy_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_signal_logs_strategy_id'), 'signal_logs', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    op.drop_index('idx_telegram_chat_id', table_name='telegram_chat_mappings')
    op.drop_index('idx_telegram_user_id', table_name='telegram_chat_mappings')
    op.drop_constraint('telegram_chat_mappings_chat_id_key', 'telegram_chat_mappings', type_='unique')
    op.create_index(op.f('ix_telegram_chat_mappings_chat_id'), 'telegram_chat_mappings', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_chat_mappings_id'), 'telegram_chat_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_chat_mappings_user_id'), 'telegram_chat_mappings', ['user_id'], unique=False)
    op.drop_constraint('timeline_events_journal_entry_id_fkey', 'timeline_events', type_='foreignkey')
    op.create_foreign_key(None, 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Trading commission in USD',
               existing_nullable=True)
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Trading commission in USD',
               existing_nullable=True)
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.create_foreign_key('timeline_events_journal_entry_id_fkey', 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_index(op.f('ix_telegram_chat_mappings_user_id'), table_name='telegram_chat_mappings')
    op.drop_index(op.f('ix_telegram_chat_mappings_id'), table_name='telegram_chat_mappings')
    op.drop_index(op.f('ix_telegram_chat_mappings_chat_id'), table_name='telegram_chat_mappings')
    op.create_unique_constraint('telegram_chat_mappings_chat_id_key', 'telegram_chat_mappings', ['chat_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_telegram_user_id', 'telegram_chat_mappings', ['user_id'], unique=False)
    op.create_index('idx_telegram_chat_id', 'telegram_chat_mappings', ['chat_id'], unique=False)
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.drop_index(op.f('ix_signal_logs_strategy_id'), table_name='signal_logs')
    op.drop_column('signal_logs', 'strategy_id')
    op.drop_index(op.f('ix_sentiment_scores_created_at'), table_name='sentiment_scores')
    op.create_index('ix_sentiment_scores_id', 'sentiment_scores', ['id'], unique=False)
    op.alter_column('sentiment_scores', 'source_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sentiment source contributions',
               existing_nullable=True)
    op.alter_column('sentiment_scores', 'score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sentiment score (-1.0 to 1.0)',
               existing_nullable=False)
    op.drop_constraint(None, 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'])
    op.add_column('open_interest', sa.Column('open_interest', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('open_interest', sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('change_in_oi', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint('uq_open_interest_contract_strike_snapshot', 'open_interest', type_='unique')
    op.drop_index('ix_open_interest_snapshot_at_symbol', table_name='open_interest')
    op.drop_index('ix_open_interest_snapshot_at', table_name='open_interest')
    op.drop_index('ix_open_interest_dte', table_name='open_interest')
    op.drop_index('ix_open_interest_contract_symbol', table_name='open_interest')
    op.create_index('idx_oi_timestamp', 'open_interest', ['timestamp'], unique=False)
    op.create_index('idx_oi_symbol', 'open_interest', ['symbol'], unique=False)
    op.alter_column('open_interest', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('open_interest', 'put_oi')
    op.drop_column('open_interest', 'call_oi')
    op.drop_column('open_interest', 'strike')
    op.drop_column('open_interest', 'dte')
    op.drop_column('open_interest', 'contract_symbol')
    op.drop_column('open_interest', 'snapshot_at')
    op.drop_constraint(None, 'mental_states', type_='foreignkey')
    op.create_foreign_key('mental_states_journal_entry_id_fkey', 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint('market_categories_name_key', 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.add_column('funds', sa.Column('initial_balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('funds', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('funds', 'risk_percentage',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('data_sources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Provider Implementation (e.g., OANDA, BINANCE)',
               existing_nullable=True)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='Provider name (e.g., OANDA, BINANCE)',
               existing_comment='User-defined alias',
               existing_nullable=False)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_candles_symbol_timeframe_timestamp', table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_column('candles', 'symbol')
    op.add_column('broker_accounts', sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_table('cot_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('commercials_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('commercials_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_commercials_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_commercials_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('managed_money_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('managed_money_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('non_reportable_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('non_reportable_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cot_records_pkey'),
    sa.UniqueConstraint('symbol', 'report_date', name='uq_cot_records_symbol_report_date', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_cot_records_symbol', 'cot_records', ['symbol'], unique=False)
    op.create_index('ix_cot_records_report_date', 'cot_records', ['report_date'], unique=False)
    op.create_table('alembic_version_pipeline',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pipeline_pkc')
    )
    op.create_table('economic_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('forecast', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='economic_events_pkey')
    )
    op.create_index('ix_economic_events_id', 'economic_events', ['id'], unique=False)
    op.create_index('ix_economic_events_external_id', 'economic_events', ['external_id'], unique=True)
    op.create_index('ix_economic_events_datetime', 'economic_events', ['datetime'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_articles_pkey')
    )
    op.create_index('ix_news_articles_symbol', 'news_articles', ['symbol'], unique=False)
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_id', 'news_articles', ['id'], unique=False)
    op.create_index('ix_news_articles_external_id', 'news_articles', ['external_id'], unique=True)
    op.drop_index(op.f('ix_strategy_execution_logs_timestamp'), table_name='strategy_execution_logs')
    op.drop_index(op.f('ix_strategy_execution_logs_deployment_id'), table_name='strategy_execution_logs')
    op.drop_table('strategy_execution_logs')
    op.drop_table('library_books')
    # ### end Alembic commands ###
