"""refactor broker_account to fund_id and add custom_code to strategy

Revision ID: 67dae91544b3
Revises: 2217d0a14157
Create Date: 2025-12-24 14:42:04.004006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67dae91544b3'
down_revision: Union[str, Sequence[str], None] = '2217d0a14157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('fund_id', sa.UUID(), nullable=False))
    op.drop_index('ix_broker_accounts_user_id', table_name='broker_accounts')
    op.drop_constraint('broker_accounts_user_id_fkey', 'broker_accounts', type_='foreignkey')
    op.drop_column('broker_accounts', 'user_id')
    op.add_column('strategies', sa.Column('custom_code', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('strategies', 'risk_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Instance-specific risk configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategies', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategies', 'risk_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Instance-specific risk configuration',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_column('strategies', 'updated_at')
    op.drop_column('strategies', 'custom_code')
    op.add_column('broker_accounts', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('broker_accounts_user_id_fkey', 'broker_accounts', 'users', ['user_id'], ['id'])
    op.create_index('ix_broker_accounts_user_id', 'broker_accounts', ['user_id'], unique=False)
    op.drop_column('broker_accounts', 'fund_id')
    # ### end Alembic commands ###
