"""Initial schema: candles, trades, strategy_runs, risk_rules

Revision ID: 6f87b5360427
Revises: 
Create Date: 2025-11-14 09:37:34.143379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f87b5360427'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading pair symbol (e.g., XAU/USD)'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe identifier (15m, 1h, 4h, D)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Candle open timestamp (UTC)'),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False, comment='Highest price'),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False, comment='Lowest price'),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False, comment='Trading volume'),
    sa.Column('ema_9_4h', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(9) on 4H timeframe (for 15m candles, aligned)'),
    sa.Column('ema_200_4h', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(200) on 4H timeframe (macro bias filter)'),
    sa.Column('ema_200_d', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(200) on Daily timeframe (macro bias filter)'),
    sa.Column('atr_14_15m', sa.Numeric(precision=18, scale=8), nullable=True, comment='ATR(14) on 15m timeframe (for stop loss calculation)'),
    sa.Column('body_to_wick_ratio', sa.Numeric(precision=5, scale=4), nullable=True, comment='Body-to-Wick Ratio (Rv) for vector candle confirmation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record creation timestamp'),
    sa.PrimaryKeyConstraint('id'),
    comment='OHLCV candlestick data with multi-timeframe indicators'
    )
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index('ix_candles_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('risk_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment="Name of the risk rule (e.g., 'MAX_RISK_PER_TRADE')"),
    sa.Column('rule_type', sa.Enum('RISK_CAP', 'LOT_SIZE', 'VOLATILITY', 'RR_RATIO', name='ruletype'), nullable=False, comment='Category of risk rule'),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Threshold value (e.g., 10.00 for $10 risk cap)'),
    sa.Column('threshold_unit', sa.String(length=20), nullable=False, comment='Unit of measurement (USD, LOT, PIPS, RATIO)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this rule is currently enforced'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of the rule'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Rule creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Rule last update timestamp'),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_name'),
    comment='Configurable risk guardrail thresholds (F2.2, F2.3, F2.4)'
    )
    op.create_table('strategy_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='Name of the strategy being tested'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Backtest start date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Backtest end date'),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Strategy parameters (EMA periods, ATR multiplier, Rv threshold, etc.)'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='Sharpe Ratio (target > 0.8)'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True, comment='Maximum Drawdown percentage (target < 15%)'),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='Win rate (winning trades / total trades)'),
    sa.Column('total_trades', sa.Integer(), nullable=True, comment='Total number of trades executed'),
    sa.Column('winning_trades', sa.Integer(), nullable=True, comment='Number of winning trades'),
    sa.Column('losing_trades', sa.Integer(), nullable=True, comment='Number of losing trades'),
    sa.Column('total_pnl_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total profit/loss in USD'),
    sa.Column('avg_win_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Average winning trade amount'),
    sa.Column('avg_loss_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Average losing trade amount'),
    sa.Column('max_consecutive_wins', sa.Integer(), nullable=True, comment='Maximum consecutive winning trades'),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True, comment='Maximum consecutive losing trades'),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=False, comment='Run execution status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if run failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Run start timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Run completion timestamp'),
    sa.CheckConstraint('end_date >= start_date', name='check_valid_date_range'),
    sa.PrimaryKeyConstraint('run_id'),
    comment='Backtest run results and performance metrics'
    )
    op.create_index('ix_strategy_runs_created_at', 'strategy_runs', ['created_at'], unique=False)
    op.create_index('ix_strategy_runs_dates', 'strategy_runs', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_strategy_runs_end_date'), 'strategy_runs', ['end_date'], unique=False)
    op.create_index(op.f('ix_strategy_runs_start_date'), 'strategy_runs', ['start_date'], unique=False)
    op.create_table('trades',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True, comment='Link to the strategy run that generated this trade'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading pair symbol (e.g., XAU/USD)'),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='Name of the strategy that generated the signal'),
    sa.Column('signal_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the signal was generated'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'REJECTED', name='tradestatus'), nullable=False, comment='Trade execution status (REJECTED tracks risk violations)'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment="Reason for trade rejection (e.g., 'Risk exceeds $10 cap')"),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False, comment='Trade direction'),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Planned or actual entry price'),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Stop loss price'),
    sa.Column('tp_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Take profit price'),
    sa.Column('lot_size', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated lot size (must be >= 0.01)'),
    sa.Column('risk_usd', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated risk in USD (must be <= $10)'),
    sa.Column('atr_pips', sa.Numeric(precision=10, scale=2), nullable=True, comment='ATR-based stop loss distance in pips'),
    sa.Column('rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='Risk-to-reward ratio (minimum 1:2)'),
    sa.Column('pnl_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Realized profit/loss in USD (for closed trades)'),
    sa.Column('mae_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum Adverse Excursion in USD'),
    sa.Column('mfe_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum Favorable Excursion in USD'),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='Actual exit price (for closed trades)'),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the trade was closed'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional trade metadata (confluence zones, indicators, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record last update timestamp'),
    sa.CheckConstraint('atr_pips <= 100.0 OR atr_pips IS NULL', name='check_max_atr_pips'),
    sa.CheckConstraint('lot_size >= 0.01', name='check_min_lot_size'),
    sa.CheckConstraint('risk_usd <= 10.00', name='check_risk_cap'),
    sa.CheckConstraint('rr_ratio >= 2.0 OR rr_ratio IS NULL', name='check_min_rr_ratio'),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trade_id'),
    comment='Individual trade records with risk and execution details'
    )
    op.create_index(op.f('ix_trades_signal_timestamp'), 'trades', ['signal_timestamp'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_strategy_run_id'), 'trades', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_timestamp'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategy_runs_start_date'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_end_date'), table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_dates', table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_created_at', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index('ix_candles_symbol_timeframe_timestamp', table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
