"""add_data_source_id_to_market_symbol

Revision ID: 6fd01a8657ee
Revises: 70e50961f785
Create Date: 2025-12-21 09:06:07.793656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd01a8657ee'
down_revision: Union[str, Sequence[str], None] = '70e50961f785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_symbols', sa.Column('data_source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.drop_column('market_symbols', 'data_source_id')
    # ### end Alembic commands ###
