"""Add sentiment fields to SignalLog

Revision ID: 7fe3421ff035
Revises: fdee558e9a1c
Create Date: 2026-01-03 11:26:35.638795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe3421ff035'
down_revision: Union[str, Sequence[str], None] = 'fdee558e9a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_logs', sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('signal_logs', sa.Column('sentiment_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_logs', 'sentiment_reason')
    op.drop_column('signal_logs', 'sentiment_score')
    # ### end Alembic commands ###
