"""Normalize Candle with market_symbol_id

Revision ID: a50606f225cd
Revises: 37554e1cfa53
Create Date: 2025-12-22 20:23:31.788719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50606f225cd'
down_revision: Union[str, Sequence[str], None] = '37554e1cfa53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('market_symbol_id', sa.UUID(), nullable=False, comment='Foreign Key to MarketSymbol (defines Symbol + DataSource)'))
    op.drop_index('ix_candles_data_source', table_name='candles')
    op.drop_index('ix_candles_symbol', table_name='candles')
    op.drop_index('ix_candles_symbol_timeframe_timestamp_source', table_name='candles')
    op.create_index(op.f('ix_candles_market_symbol_id'), 'candles', ['market_symbol_id'], unique=False)
    op.create_index('ix_candles_market_symbol_timeframe_timestamp', 'candles', ['market_symbol_id', 'timeframe', 'timestamp'], unique=True)
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.drop_column('candles', 'symbol')
    op.drop_column('candles', 'data_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('data_source', sa.VARCHAR(length=50), server_default=sa.text("'OANDA'::character varying"), autoincrement=False, nullable=False, comment='Source of data (e.g. OANDA, BINANCE)'))
    op.add_column('candles', sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Trading pair symbol (e.g., XAU/USD)'))
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.drop_index('ix_candles_market_symbol_timeframe_timestamp', table_name='candles')
    op.drop_index(op.f('ix_candles_market_symbol_id'), table_name='candles')
    op.create_index('ix_candles_symbol_timeframe_timestamp_source', 'candles', ['symbol', 'timeframe', 'timestamp', 'data_source'], unique=True)
    op.create_index('ix_candles_symbol', 'candles', ['symbol'], unique=False)
    op.create_index('ix_candles_data_source', 'candles', ['data_source'], unique=False)
    op.drop_column('candles', 'market_symbol_id')
    # ### end Alembic commands ###
