"""Add broker_accounts table and update trades

Revision ID: a729b4d32520
Revises: 6fd01a8657ee
Create Date: 2025-12-22 10:15:21.119187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a729b4d32520'
down_revision: Union[str, Sequence[str], None] = '6fd01a8657ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('credentials_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trades', sa.Column('broker_account_id', sa.UUID(), nullable=True))
    op.alter_column('trades', 'strategy_run_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to the strategy run that generated this trade',
               existing_nullable=True)
    op.alter_column('trades', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.drop_index('ix_trades_strategy_run_id', table_name='trades')
    op.drop_constraint('trades_strategy_run_id_fkey', 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'broker_accounts', ['broker_account_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'strategy_runs', ['strategy_run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key('trades_strategy_run_id_fkey', 'trades', 'strategy_runs', ['strategy_run_id'], ['run_id'], ondelete='SET NULL')
    op.create_index('ix_trades_strategy_run_id', 'trades', ['strategy_run_id'], unique=False)
    op.alter_column('trades', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.alter_column('trades', 'strategy_run_id',
               existing_type=sa.UUID(),
               comment='Link to the strategy run that generated this trade',
               existing_nullable=True)
    op.drop_column('trades', 'broker_account_id')
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###
