"""Add signal_logs table

Revision ID: b1d0923173ff
Revises: 07fc82dbba14
Create Date: 2025-12-30 23:20:12.220976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d0923173ff'
down_revision: Union[str, Sequence[str], None] = '07fc82dbba14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_logs_deployment_id'), 'signal_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_signal_logs_symbol'), 'signal_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_signal_logs_timestamp'), 'signal_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_logs_timestamp'), table_name='signal_logs')
    op.drop_index(op.f('ix_signal_logs_symbol'), table_name='signal_logs')
    op.drop_index(op.f('ix_signal_logs_deployment_id'), table_name='signal_logs')
    op.drop_table('signal_logs')
    # ### end Alembic commands ###
