"""olympus_v2_schema

Revision ID: b26d5044f048
Revises: dd35e97a4229
Create Date: 2025-12-31 23:46:41.148107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26d5044f048'
down_revision: Union[str, Sequence[str], None] = 'dd35e97a4229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('logic_schema_version', sa.String(), nullable=True),
    sa.Column('logic_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mental_hand_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('pre_trade_emotion', sa.String(length=50), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('irrational_thought', sa.Text(), nullable=True),
    sa.Column('behavioral_result', sa.Text(), nullable=True),
    sa.Column('correction_logic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('robustness_score', sa.Integer(), nullable=False),
    sa.Column('sharpe_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('car_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_dd_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('car_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_dd_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('volatility_target', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_rebalance', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('strategies', sa.Column('config_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'strategies', 'strategy_configs', ['config_id'], ['id'])
    op.add_column('users', sa.Column('reputation_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_verified_quant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified_quant')
    op.drop_column('users', 'reputation_score')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'config_id')
    op.drop_table('portfolio_allocations')
    op.drop_table('strategy_validations')
    op.drop_table('mental_hand_histories')
    op.drop_table('strategy_configs')
    # ### end Alembic commands ###
