"""add_cascade_delete_to_deployments

Revision ID: bad435639de1
Revises: b1d0923173ff
Create Date: 2025-12-31 00:38:57.633819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad435639de1'
down_revision: Union[str, Sequence[str], None] = 'b1d0923173ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deployments_strategy_id_fkey', 'deployments', type_='foreignkey')
    op.create_foreign_key(None, 'deployments', 'saved_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.create_foreign_key('deployments_strategy_id_fkey', 'deployments', 'saved_strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###
