"""Add user_preferences table with strategy configuration

Revision ID: c449a6e4c0e0
Revises: f268a4306fa2
Create Date: 2025-12-04 16:45:36.728198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c449a6e4c0e0'
down_revision: Union[str, Sequence[str], None] = 'f268a4306fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
