"""add_cascade_delete_to_chat_sessions

Revision ID: dd35e97a4229
Revises: bad435639de1
Create Date: 2025-12-31 01:13:56.758545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd35e97a4229'
down_revision: Union[str, Sequence[str], None] = 'bad435639de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_sessions_strategy_id_fkey', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'saved_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_strategy_id_fkey', 'chat_sessions', 'saved_strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###
