"""Add is_complete to candles

Revision ID: e1533908c87a
Revises: 8a1965934aab
Create Date: 2025-12-08 09:26:20.119201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1533908c87a'
down_revision: Union[str, Sequence[str], None] = '8a1965934aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('is_complete', sa.Boolean(), nullable=True, comment='Whether the candle is closed/complete'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles', 'is_complete')
    # ### end Alembic commands ###
