"""add system_config and candle indicators

Revision ID: f3f7ff98c665
Revises: 53f28d1e3a44
Create Date: 2025-12-22 16:26:33.293669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3f7ff98c665'
down_revision: Union[str, Sequence[str], None] = '53f28d1e3a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment="Config key (e.g. 'supported_timeframes')"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Config value (JSON)'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.add_column('candles', sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible storage for calculated indicators (RSI, EMA, etc.)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candles', 'indicators')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
