"""fresh_initial_schema

Revision ID: fdee558e9a1c
Revises: 
Create Date: 2026-01-02 04:49:00.950931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdee558e9a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Provider name (e.g., OANDA, BINANCE)'),
    sa.Column('type', sa.String(), nullable=False, comment='Type of data source (e.g., api, csv, db)'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Connection details (API keys, URLs) - Encrypted in app'),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected data schema (e.g., column names for CSV, API response structure)'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tool_call', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_component'), 'decision_logs', ['component'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('strategy_type', sa.Enum('MTF_SMC_BASIC', 'LONG_SHORT_EQUITY', 'MACRO_TACTICAL', 'MULTI_ASSET', name='strategy_type_enum'), nullable=False),
    sa.Column('asset_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_risk_per_trade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('default_lot_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_drawdown_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_portfolio_beta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gross_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('net_exposure_limit', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position_limit_single', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('position_limit_sector', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.create_table('plugins',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('ALPHA', 'RISK', 'EXECUTION', 'UTILITY', name='plugin_category'), nullable=False),
    sa.Column('base_config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment="Name of the risk rule (e.g., 'MAX_RISK_PER_TRADE')"),
    sa.Column('rule_type', sa.Enum('RISK_CAP', 'LOT_SIZE', 'VOLATILITY', 'RR_RATIO', name='ruletype'), nullable=False, comment='Category of risk rule'),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=False, comment='Threshold value (e.g., 10.00 for $10 risk cap)'),
    sa.Column('threshold_unit', sa.String(length=20), nullable=False, comment='Unit of measurement (USD, LOT, PIPS, RATIO)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this rule is currently enforced'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description of the rule'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Rule creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Rule last update timestamp'),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_name'),
    comment='Configurable risk guardrail thresholds (F2.2, F2.3, F2.4)'
    )
    op.create_table('strategy_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='Name of the strategy being tested'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Backtest start date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Backtest end date'),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Strategy parameters (EMA periods, ATR multiplier, Rv threshold, etc.)'),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='Sharpe Ratio (target > 0.8)'),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=True, comment='Maximum Drawdown percentage (target < 15%)'),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='Win rate (winning trades / total trades)'),
    sa.Column('total_trades', sa.Integer(), nullable=True, comment='Total number of trades executed'),
    sa.Column('winning_trades', sa.Integer(), nullable=True, comment='Number of winning trades'),
    sa.Column('losing_trades', sa.Integer(), nullable=True, comment='Number of losing trades'),
    sa.Column('total_pnl_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total profit/loss in USD'),
    sa.Column('avg_win_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Average winning trade amount'),
    sa.Column('avg_loss_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Average losing trade amount'),
    sa.Column('max_consecutive_wins', sa.Integer(), nullable=True, comment='Maximum consecutive winning trades'),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True, comment='Maximum consecutive losing trades'),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='runstatus'), nullable=False, comment='Run execution status'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if run failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Run start timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Run completion timestamp'),
    sa.CheckConstraint('end_date >= start_date', name='check_valid_date_range'),
    sa.PrimaryKeyConstraint('run_id'),
    comment='Backtest run results and performance metrics'
    )
    op.create_index('ix_strategy_runs_created_at', 'strategy_runs', ['created_at'], unique=False)
    op.create_index('ix_strategy_runs_dates', 'strategy_runs', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_strategy_runs_end_date'), 'strategy_runs', ['end_date'], unique=False)
    op.create_index(op.f('ix_strategy_runs_start_date'), 'strategy_runs', ['start_date'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment="Config key (e.g. 'supported_timeframes')"),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Config value (JSON)'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('is_verified_quant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('backtest_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('execution_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('best_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['backtest_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('credentials_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('supported_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_amount', sa.Float(), nullable=True),
    sa.Column('pnl_r', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('take_profit_price', sa.Float(), nullable=True),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('context_score', sa.Integer(), nullable=True),
    sa.Column('game_level', sa.Enum('A_GAME', 'B_GAME', 'C_GAME', name='gamelevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_trade_id'), 'journal_entries', ['trade_id'], unique=True)
    op.create_table('market_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['market_categories.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Persisted backtest metrics and plot'),
    sa.Column('last_optimization_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_simulation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('logic_schema_version', sa.String(), nullable=True),
    sa.Column('logic_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('trading_account', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'TRADER', 'VIEWER', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plugins',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plugin_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_fund_id', sa.UUID(), nullable=True),
    sa.Column('preferred_timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Preferred trading timeframes'),
    sa.Column('default_symbol', sa.String(length=20), nullable=False),
    sa.Column('session_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Trading session preferences: LONDON, NY, ASIA'),
    sa.Column('telegram_bot_token', sa.String(), nullable=True, comment="Encrypted Telegram bot token for user's personal bot"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['default_fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_symbol_id', sa.UUID(), nullable=False, comment='Foreign Key to MarketSymbol (defines Symbol + DataSource)'),
    sa.Column('symbol', sa.String(), nullable=True, comment='Denormalized symbol for quick lookup'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe identifier (15m, 1h, 4h, D)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Candle open timestamp (UTC)'),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=False, comment='Highest price'),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=False, comment='Lowest price'),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.Numeric(precision=18, scale=8), nullable=False, comment='Trading volume'),
    sa.Column('is_complete', sa.Boolean(), nullable=True, comment='Whether the candle is closed/complete'),
    sa.Column('ema_9_4h', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(9) on 4H timeframe (for 15m candles, aligned)'),
    sa.Column('ema_200_4h', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(200) on 4H timeframe (macro bias filter)'),
    sa.Column('ema_200_d', sa.Numeric(precision=18, scale=8), nullable=True, comment='EMA(200) on Daily timeframe (macro bias filter)'),
    sa.Column('atr_14_15m', sa.Numeric(precision=18, scale=8), nullable=True, comment='ATR(14) on 15m timeframe (for stop loss calculation)'),
    sa.Column('body_to_wick_ratio', sa.Numeric(precision=5, scale=4), nullable=True, comment='Body-to-Wick Ratio (Rv) for vector candle confirmation'),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible storage for calculated indicators (RSI, EMA, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['market_symbol_id'], ['market_symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='OHLCV candlestick data with multi-timeframe indicators'
    )
    op.create_index(op.f('ix_candles_market_symbol_id'), 'candles', ['market_symbol_id'], unique=False)
    op.create_index('ix_candles_market_symbol_timeframe_timestamp', 'candles', ['market_symbol_id', 'timeframe', 'timestamp'], unique=True)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['saved_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_strategy_id'), 'chat_sessions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['saved_strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_strategy_id'), 'deployments', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_deployments_user_id'), 'deployments', ['user_id'], unique=False)
    op.create_table('mental_hand_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('pre_trade_emotion', sa.String(length=50), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('irrational_thought', sa.Text(), nullable=True),
    sa.Column('behavioral_result', sa.Text(), nullable=True),
    sa.Column('correction_logic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mental_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('greed_level', sa.Integer(), nullable=True),
    sa.Column('fear_level', sa.Integer(), nullable=True),
    sa.Column('tilt_level', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('discipline_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('root_cause_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('why_exist', sa.Text(), nullable=True),
    sa.Column('flaw', sa.Text(), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('logic', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=False, comment="Identifier for the strategy logic template (e.g., 'SMC_V1')"),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Strategy-specific configuration parameters (overrides template defaults)'),
    sa.Column('risk_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('custom_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_backtest_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_optimization_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_simulation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['strategy_configs.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('robustness_score', sa.Integer(), nullable=False),
    sa.Column('sharpe_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('car_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_dd_train', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('car_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_dd_test', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('strategy_run_id', sa.UUID(), nullable=True),
    sa.Column('broker_account_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='Name of the strategy that generated the signal'),
    sa.Column('signal_timestamp', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the signal was generated'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'REJECTED', name='tradestatus'), nullable=False, comment='Trade execution status (REJECTED tracks risk violations)'),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True, comment="Reason for trade rejection (e.g., 'Risk exceeds $10 cap')"),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False, comment='Trade direction'),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Planned or actual entry price'),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Stop loss price'),
    sa.Column('tp_price', sa.Numeric(precision=18, scale=8), nullable=False, comment='Take profit price'),
    sa.Column('lot_size', sa.Numeric(precision=12, scale=6), nullable=False, comment='Calculated lot size (must be >= 0.01)'),
    sa.Column('risk_usd', sa.Numeric(precision=10, scale=2), nullable=False, comment='Calculated risk in USD (must be <= $10)'),
    sa.Column('atr_pips', sa.Numeric(precision=10, scale=2), nullable=True, comment='ATR-based stop loss distance in pips'),
    sa.Column('rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='Risk-to-reward ratio (minimum 1:2)'),
    sa.Column('pnl_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Realized profit/loss in USD (for closed trades)'),
    sa.Column('mae_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum Adverse Excursion in USD'),
    sa.Column('mfe_usd', sa.Numeric(precision=10, scale=2), nullable=True, comment='Maximum Favorable Excursion in USD'),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='Actual exit price (for closed trades)'),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the trade was closed'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional trade metadata (confluence zones, indicators, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record last update timestamp'),
    sa.CheckConstraint('atr_pips <= 100.0 OR atr_pips IS NULL', name='check_max_atr_pips'),
    sa.CheckConstraint('lot_size > 0', name='check_min_lot_size'),
    sa.CheckConstraint('risk_usd <= 10.00', name='check_risk_cap'),
    sa.CheckConstraint('rr_ratio >= 2.0 OR rr_ratio IS NULL', name='check_min_rr_ratio'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.run_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    comment='Individual trade records with risk and execution details'
    )
    op.create_index(op.f('ix_trades_broker_account_id'), 'trades', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_trades_signal_timestamp'), 'trades', ['signal_timestamp'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_strategy_run_id'), 'trades', ['strategy_run_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('portfolio_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('volatility_target', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_rebalance', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='CREATED', nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sentiment_reason', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_logs_deployment_id'), 'signal_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_signal_logs_symbol'), 'signal_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_signal_logs_timestamp'), 'signal_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_logs_timestamp'), table_name='signal_logs')
    op.drop_index(op.f('ix_signal_logs_symbol'), table_name='signal_logs')
    op.drop_index(op.f('ix_signal_logs_deployment_id'), table_name='signal_logs')
    op.drop_table('signal_logs')
    op.drop_table('portfolio_allocations')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_broker_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('timeline_events')
    op.drop_table('strategy_validations')
    op.drop_table('strategies')
    op.drop_table('root_cause_analyses')
    op.drop_table('mental_states')
    op.drop_table('mental_hand_histories')
    op.drop_index(op.f('ix_deployments_user_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_strategy_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_strategy_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index('ix_candles_market_symbol_timeframe_timestamp', table_name='candles')
    op.drop_index(op.f('ix_candles_market_symbol_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_table('user_preferences')
    op.drop_table('user_plugins')
    op.drop_table('user_funds')
    op.drop_table('transactions')
    op.drop_table('strategy_configs')
    op.drop_table('saved_strategies')
    op.drop_table('market_symbols')
    op.drop_index(op.f('ix_journal_entries_trade_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('broker_accounts')
    op.drop_table('backtest_history')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_strategy_runs_start_date'), table_name='strategy_runs')
    op.drop_index(op.f('ix_strategy_runs_end_date'), table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_dates', table_name='strategy_runs')
    op.drop_index('ix_strategy_runs_created_at', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('risk_rules')
    op.drop_table('plugins')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.drop_table('market_categories')
    op.drop_table('funds')
    op.drop_index(op.f('ix_decision_logs_component'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_table('data_sources')
    op.drop_table('backtest_configs')
    # ### end Alembic commands ###
