"""enforce_1to1_telegram_mapping

Revision ID: 0c2a22f5bd76
Revises: c1b94a3f0277
Create Date: 2026-03-23 05:14:32.851709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2a22f5bd76'
down_revision = 'c1b94a3f0277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_chat_mappings_user_id'), table_name='telegram_chat_mappings')
    op.create_index(op.f('ix_telegram_chat_mappings_user_id'), 'telegram_chat_mappings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_chat_mappings_user_id'), table_name='telegram_chat_mappings')
    op.create_index(op.f('ix_telegram_chat_mappings_user_id'), 'telegram_chat_mappings', ['user_id'], unique=False)
    # ### end Alembic commands ###
