"""add fund_id to deployments

Revision ID: 0f4b4407368d
Revises: 39654befddaf
Create Date: 2026-03-11 05:02:11.436424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4b4407368d'
down_revision = '39654befddaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('fund_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_deployments_fund_id'), 'deployments', ['fund_id'], unique=False)
    op.create_foreign_key(None, 'deployments', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_index(op.f('ix_deployments_fund_id'), table_name='deployments')
    op.drop_column('deployments', 'fund_id')
    # ### end Alembic commands ###
