"""Add updated_at to Candle model

Revision ID: 1538ce20ec3a
Revises: 4833c32da739
Create Date: 2025-12-09 04:33:12.956704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1538ce20ec3a'
down_revision = '4833c32da739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration should only add the 'updated_at' column to the 'candles' table.
    # It should not drop any tables or indices belonging to other services.
    op.add_column('candles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # The following 'alter_column' calls are benign as they just set/clear comments or alter existing types to the same type,
    # but we will keep them as they don't cause issues and were auto-generated to reflect the model's metadata.
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.alter_column('candles', 'timeframe',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Timeframe identifier (15m, 1h, 4h, D)',
               existing_nullable=False)
    op.alter_column('candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Candle open timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('candles', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Opening price',
               existing_nullable=False)
    op.alter_column('candles', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Highest price',
               existing_nullable=False)
    op.alter_column('candles', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Lowest price',
               existing_nullable=False)
    op.alter_column('candles', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Closing price',
               existing_nullable=False)
    op.alter_column('candles', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Trading volume',
               existing_nullable=False)
    op.alter_column('candles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the candle is closed/complete',
               existing_nullable=True)
    op.alter_column('candles', 'ema_9_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(9) on 4H timeframe (for 15m candles, aligned)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(200) on 4H timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_d',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='EMA(200) on Daily timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'atr_14_15m',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='ATR(14) on 15m timeframe (for stop loss calculation)',
               existing_nullable=True)
    op.alter_column('candles', 'body_to_wick_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Body-to-Wick Ratio (Rv) for vector candle confirmation',
               existing_nullable=True)
    op.alter_column('candles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Record creation timestamp',
               existing_nullable=True)
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_table_comment(
        'candles',
        existing_comment='OHLCV candlestick data with multi-timeframe indicators',
        schema=None
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This downgrade should only remove the 'updated_at' column from the 'candles' table.
    # It should not create any tables or indices belonging to other services.
    op.create_table_comment(
        'candles',
        'OHLCV candlestick data with multi-timeframe indicators',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.alter_column('candles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Record creation timestamp',
               existing_nullable=True)
    op.alter_column('candles', 'body_to_wick_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Body-to-Wick Ratio (Rv) for vector candle confirmation',
               existing_nullable=True)
    op.alter_column('candles', 'atr_14_15m',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='ATR(14) on 15m timeframe (for stop loss calculation)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_d',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(200) on Daily timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_200_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(200) on 4H timeframe (macro bias filter)',
               existing_nullable=True)
    op.alter_column('candles', 'ema_9_4h',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='EMA(9) on 4H timeframe (for 15m candles, aligned)',
               existing_nullable=True)
    op.alter_column('candles', 'is_complete',
               existing_type=sa.BOOLEAN(),
               comment='Whether the candle is closed/complete',
               existing_nullable=True)
    op.alter_column('candles', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Trading volume',
               existing_nullable=False)
    op.alter_column('candles', 'close',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Closing price',
               existing_nullable=False)
    op.alter_column('candles', 'low',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Lowest price',
               existing_nullable=False)
    op.alter_column('candles', 'high',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Highest price',
               existing_nullable=False)
    op.alter_column('candles', 'open',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Opening price',
               existing_nullable=False)
    op.alter_column('candles', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Candle open timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('candles', 'timeframe',
               existing_type=sa.VARCHAR(length=10),
               comment='Timeframe identifier (15m, 1h, 4h, D)',
               existing_nullable=False)
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.drop_column('candles', 'updated_at')
    # ### end Alembic commands ###
