"""fix(trade): sync commission comment with spec

Revision ID: 19dd1ee38767
Revises: 2b1f428e7612
Create Date: 2026-03-30 11:59:05.487465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd1ee38767'
down_revision = '2b1f428e7612'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Trading commission in USD (System Estimate or Reconciled)',
               existing_comment='Trading commission in USD',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Trading commission in USD',
               existing_comment='Trading commission in USD (System Estimate or Reconciled)',
               existing_nullable=True)
    # ### end Alembic commands ###
