"""Add category, relevance_score, and impact_rationale to NewsArticle

Revision ID: 2263d8e0ed20
Revises: 2a24e69d8c71
Create Date: 2026-03-23 08:31:57.141878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2263d8e0ed20'
down_revision = '2a24e69d8c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('category', sa.String(), nullable=True))
    op.add_column('news_articles', sa.Column('relevance_score', sa.Integer(), nullable=True))
    op.add_column('news_articles', sa.Column('impact_rationale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'impact_rationale')
    op.drop_column('news_articles', 'relevance_score')
    op.drop_column('news_articles', 'category')
    # ### end Alembic commands ###
