"""Restore dropped sentiment_scores table and missing columns

Revision ID: 2769a2d00d26
Revises: 2d8e2a8e29d3
Create Date: 2026-02-28 23:52:37.030186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2769a2d00d26'
down_revision: Union[str, Sequence[str], None] = '2d8e2a8e29d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False, comment='Sentiment score (-1.0 to 1.0)'),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sentiment source contributions'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_created_at'), 'sentiment_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_symbol'), 'sentiment_scores', ['symbol'], unique=False)
    op.add_column('open_interest', sa.Column('underlying_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('trades', sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True, comment='Trading commission in USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'commission')
    op.drop_column('open_interest', 'underlying_price')
    op.drop_index(op.f('ix_sentiment_scores_symbol'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_created_at'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    # ### end Alembic commands ###
