"""Restore dropped sentiment_scores table and missing columns

Revision ID: 2769a2d00d26
Revises: 2d8e2a8e29d3
Create Date: 2026-02-28 23:52:37.030186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2769a2d00d26'
down_revision: Union[str, Sequence[str], None] = '2d8e2a8e29d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_interest', sa.Column('underlying_price', sa.Numeric(precision=18, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'commission')
    op.drop_column('open_interest', 'underlying_price')
    # ### end Alembic commands ###
