"""fix_memory_vector_dimension

Revision ID: 2845c0a22860
Revises: 586ac82c8591
Create Date: 2026-03-20 21:57:41.214348

"""
from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '2845c0a22860'
down_revision = '586ac82c8591'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
