"""align_data_source_comment

Revision ID: 2a24e69d8c71
Revises: 9c0e4b93a140
Create Date: 2026-03-23 05:41:56.558885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a24e69d8c71'
down_revision = '9c0e4b93a140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Encrypted connection details (API keys, URLs) - Base64 String',
               existing_comment='Connection details (API keys, URLs) - Encrypted in app',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Connection details (API keys, URLs) - Encrypted in app',
               existing_comment='Encrypted connection details (API keys, URLs) - Base64 String',
               existing_nullable=False)
    # ### end Alembic commands ###
