"""verify_models_final

Revision ID: 30ae3ae23514
Revises: 59cdfb687038
Create Date: 2026-03-07 02:32:53.669241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30ae3ae23514'
down_revision = '59cdfb687038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('audit_logs')
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('api_keys_api_key_key'), 'api_keys', type_='unique')
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    op.alter_column('broker_accounts', 'account_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PRACTICE'::character varying"))
    op.drop_constraint(op.f('broker_accounts_fund_id_fkey'), 'broker_accounts', type_='foreignkey')
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(),
               comment='Trading pair symbol (e.g., XAU/USD)',
               existing_comment='Denormalized symbol for quick lookup',
               existing_nullable=False)
    op.drop_index(op.f('ix_candles_market_symbol_id'), table_name='candles')
    op.drop_index(op.f('ix_candles_market_symbol_timeframe_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol_timeframe_timestamp'), table_name='candles')
    op.create_index('ix_candles_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.drop_constraint(op.f('candles_market_symbol_id_fkey'), 'candles', type_='foreignkey')
    op.drop_column('candles', 'market_symbol_id')
    op.drop_column('candles', 'indicators')
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='Provider name (e.g., OANDA, BINANCE)',
               existing_comment='User-defined alias',
               existing_nullable=False)
    op.drop_column('data_sources', 'provider')
    op.alter_column('deployments', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('deployments', 'status',
               existing_type=postgresql.ENUM('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_strategy_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_user_id'), table_name='deployments')
    op.drop_constraint(op.f('deployments_user_id_fkey'), 'deployments', type_='foreignkey')
    op.drop_constraint(op.f('deployments_strategy_id_fkey'), 'deployments', type_='foreignkey')
    op.alter_column('library_books', 'last_ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('market_categories_name_key'), 'market_categories', type_='unique')
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.alter_column('saved_strategies', 'last_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Persisted backtest metrics and plot',
               existing_nullable=True)
    op.drop_constraint(op.f('saved_strategies_user_id_fkey'), 'saved_strategies', type_='foreignkey')
    op.drop_column('saved_strategies', 'updated_at')
    op.drop_column('saved_strategies', 'description')
    op.drop_column('saved_strategies', 'created_at')
    op.drop_index(op.f('ix_signal_logs_strategy_id'), table_name='signal_logs')
    op.drop_constraint(op.f('signal_logs_deployment_id_fkey'), 'signal_logs', type_='foreignkey')
    op.drop_constraint(op.f('signal_logs_strategy_id_fkey'), 'signal_logs', type_='foreignkey')
    op.drop_column('signal_logs', 'strategy_id')
    op.alter_column('strategies', 'template_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Identifier for the strategy logic template (e.g., 'SMC_V1')",
               existing_nullable=False)
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_nullable=False)
    op.drop_constraint(op.f('strategies_broker_account_id_fkey'), 'strategies', type_='foreignkey')
    op.drop_constraint(op.f('strategies_fund_id_fkey'), 'strategies', type_='foreignkey')
    op.drop_constraint(op.f('strategies_config_id_fkey'), 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'config_id')
    op.drop_index(op.f('idx_telegram_chat_id'), table_name='telegram_chat_mappings')
    op.drop_index(op.f('idx_telegram_user_id'), table_name='telegram_chat_mappings')
    op.drop_constraint(op.f('telegram_chat_mappings_chat_id_key'), 'telegram_chat_mappings', type_='unique')
    op.create_index(op.f('ix_telegram_chat_mappings_chat_id'), 'telegram_chat_mappings', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_chat_mappings_id'), 'telegram_chat_mappings', ['id'], unique=False)
    op.add_column('trades', sa.Column('trailing_stop', sa.Boolean(), nullable=True, comment='Enable/Disable trailing stop loss'))
    op.alter_column('trades', 'broker_trade_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Official trade ID from broker',
               existing_nullable=True)
    op.add_column('user_preferences', sa.Column('ctrader_janitor_enabled', sa.Boolean(), nullable=False, comment='Allow system to reconcile cTrader positions'))
    op.alter_column('user_preferences', 'oanda_janitor_enabled',
               existing_type=sa.BOOLEAN(),
               comment='Allow system to reconcile OANDA positions',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'oanda_janitor_enabled',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Allow system to reconcile OANDA positions',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('user_preferences', 'ctrader_janitor_enabled')
    op.alter_column('trades', 'broker_trade_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Official trade ID from broker',
               existing_nullable=True)
    op.drop_column('trades', 'trailing_stop')
    op.drop_index(op.f('ix_telegram_chat_mappings_id'), table_name='telegram_chat_mappings')
    op.drop_index(op.f('ix_telegram_chat_mappings_chat_id'), table_name='telegram_chat_mappings')
    op.create_unique_constraint(op.f('telegram_chat_mappings_chat_id_key'), 'telegram_chat_mappings', ['chat_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_telegram_user_id'), 'telegram_chat_mappings', ['user_id'], unique=False)
    op.create_index(op.f('idx_telegram_chat_id'), 'telegram_chat_mappings', ['chat_id'], unique=False)
    op.add_column('strategies', sa.Column('config_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('strategies_config_id_fkey'), 'strategies', 'strategy_configs', ['config_id'], ['id'])
    op.create_foreign_key(op.f('strategies_fund_id_fkey'), 'strategies', 'funds', ['fund_id'], ['id'])
    op.create_foreign_key(op.f('strategies_broker_account_id_fkey'), 'strategies', 'broker_accounts', ['broker_account_id'], ['id'])
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_nullable=False)
    op.alter_column('strategies', 'template_id',
               existing_type=sa.VARCHAR(),
               comment="Identifier for the strategy logic template (e.g., 'SMC_V1')",
               existing_nullable=False)
    op.add_column('signal_logs', sa.Column('strategy_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('signal_logs_strategy_id_fkey'), 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    op.create_foreign_key(op.f('signal_logs_deployment_id_fkey'), 'signal_logs', 'deployments', ['deployment_id'], ['id'])
    op.create_index(op.f('ix_signal_logs_strategy_id'), 'signal_logs', ['strategy_id'], unique=False)
    op.add_column('saved_strategies', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('saved_strategies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('saved_strategies', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('saved_strategies_user_id_fkey'), 'saved_strategies', 'users', ['user_id'], ['id'])
    op.alter_column('saved_strategies', 'last_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Persisted backtest metrics and plot',
               existing_nullable=True)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint(op.f('market_categories_name_key'), 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('library_books', 'last_ingested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_foreign_key(op.f('deployments_strategy_id_fkey'), 'deployments', 'saved_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('deployments_user_id_fkey'), 'deployments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_deployments_user_id'), 'deployments', ['user_id'], unique=False)
    op.create_index(op.f('ix_deployments_strategy_id'), 'deployments', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.alter_column('deployments', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               nullable=False)
    op.alter_column('deployments', 'config_snapshot',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('data_sources', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Provider Implementation (e.g., OANDA, BINANCE)'))
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='User-defined alias',
               existing_comment='Provider name (e.g., OANDA, BINANCE)',
               existing_nullable=False)
    op.add_column('candles', sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Flexible storage for calculated indicators (RSI, EMA, etc.)'))
    op.add_column('candles', sa.Column('market_symbol_id', sa.UUID(), autoincrement=False, nullable=False, comment='Foreign Key to MarketSymbol (defines Symbol + DataSource)'))
    op.create_foreign_key(op.f('candles_market_symbol_id_fkey'), 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.drop_index('ix_candles_symbol_timeframe_timestamp', table_name='candles')
    op.create_index(op.f('ix_candles_symbol_timeframe_timestamp'), 'candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_market_symbol_timeframe_timestamp'), 'candles', ['market_symbol_id', 'timeframe', 'timestamp'], unique=True)
    op.create_index(op.f('ix_candles_market_symbol_id'), 'candles', ['market_symbol_id'], unique=False)
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(),
               comment='Denormalized symbol for quick lookup',
               existing_comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.create_foreign_key(op.f('broker_accounts_fund_id_fkey'), 'broker_accounts', 'funds', ['fund_id'], ['id'])
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PRACTICE'::character varying"))
    op.alter_column('broker_accounts', 'account_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.create_unique_constraint(op.f('api_keys_api_key_key'), 'api_keys', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('audit_logs_pkey'))
    )
    op.drop_table('system_prompts')
    op.drop_table('prompt_audit_logs')
    # ### end Alembic commands ###
