"""allow_null_sl_tp

Revision ID: 35208bf0cf57
Revises: 26a80d551e73
Create Date: 2026-03-19 11:59:47.887396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35208bf0cf57'
down_revision = '26a80d551e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'sl_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True,
               existing_comment='Stop loss price')
    op.alter_column('trades', 'tp_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True,
               existing_comment='Take profit price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'tp_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False,
               existing_comment='Take profit price')
    op.alter_column('trades', 'sl_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False,
               existing_comment='Stop loss price')
    # ### end Alembic commands ###
