
"""Add rich trade data columns

Revision ID: 36321cdd9c03
Revises: da3a948ef7c6
Create Date: 2026-02-14 05:06:13.844558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36321cdd9c03'
down_revision = 'da3a948ef7c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFELY ADD NEW COLUMNS ONLY
    op.add_column('trades', sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('swap', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('gross_pnl', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('broker_trade_id', sa.String(length=50), nullable=True))
    op.add_column('trades', sa.Column('broker_deal_id', sa.String(length=50), nullable=True))
    
    op.create_index(op.f('ix_trades_broker_trade_id'), 'trades', ['broker_trade_id'], unique=False)
    op.create_unique_constraint(None, 'trades', ['broker_deal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_index(op.f('ix_trades_broker_trade_id'), table_name='trades')
    
    op.drop_column('trades', 'broker_deal_id')
    op.drop_column('trades', 'broker_trade_id')
    op.drop_column('trades', 'gross_pnl')
    op.drop_column('trades', 'swap')
    op.drop_column('trades', 'commission')
    # ### end Alembic commands ###
