
"""Add rich trade data columns

Revision ID: 36321cdd9c03
Revises: da3a948ef7c6
Create Date: 2026-02-14 05:06:13.844558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36321cdd9c03'
down_revision = 'da3a948ef7c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SAFELY ADD NEW COLUMNS ONLY
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('trades')]
    
    if 'commission' not in columns:
        op.add_column('trades', sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True))
    if 'swap' not in columns:
        op.add_column('trades', sa.Column('swap', sa.Numeric(precision=10, scale=2), nullable=True))
    if 'gross_pnl' not in columns:
        op.add_column('trades', sa.Column('gross_pnl', sa.Numeric(precision=10, scale=2), nullable=True))
    if 'broker_trade_id' not in columns:
        op.add_column('trades', sa.Column('broker_trade_id', sa.String(length=50), nullable=True))
    if 'broker_deal_id' not in columns:
        op.add_column('trades', sa.Column('broker_deal_id', sa.String(length=50), nullable=True))
    
    # Check if index exists
    indices = [i['name'] for i in inspector.get_indexes('trades')]
    if 'ix_trades_broker_trade_id' not in indices:
        op.create_index(op.f('ix_trades_broker_trade_id'), 'trades', ['broker_trade_id'], unique=False)
    
    # Check if unique constraint exists (simplified check)
    try:
        op.create_unique_constraint(None, 'trades', ['broker_deal_id'])
    except Exception:
        # Constraint might already exist
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_index(op.f('ix_trades_broker_trade_id'), table_name='trades')
    
    op.drop_column('trades', 'broker_deal_id')
    op.drop_column('trades', 'broker_trade_id')
    op.drop_column('trades', 'gross_pnl')
    op.drop_column('trades', 'swap')
    op.drop_column('trades', 'commission')
    # ### end Alembic commands ###
