"""add_decision_logs_and_sync_metadata

Revision ID: 39654befddaf
Revises: 9541dec11a94
Create Date: 2026-03-07 12:53:15.038953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39654befddaf'
down_revision = '9541dec11a94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tool_call', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_component'), 'decision_logs', ['component'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_component'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
