"""Add Phase 9 Knowledge fields v2

Revision ID: 448e5a59cf50
Revises: 2845c0a22860
Create Date: 2026-03-21 07:06:47.645704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '448e5a59cf50'
down_revision = '2845c0a22860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_logs', sa.Column('knowledge_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('signal_logs', sa.Column('knowledge_score', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('trades', sa.Column('knowledge_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='GraphRAG context snapshot from FalkorDB'))
    op.add_column('trades', sa.Column('knowledge_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='Semantic confidence score (0.0 to 1.5)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'knowledge_score')
    op.drop_column('trades', 'knowledge_context')
    op.drop_column('signal_logs', 'knowledge_score')
    op.drop_column('signal_logs', 'knowledge_context')
    # ### end Alembic commands ###
