"""Add updated_at to users

Revision ID: 4b9c6dd54fc7
Revises: f97fb85ac765
Create Date: 2026-01-10 10:17:37.457580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9c6dd54fc7'
down_revision: Union[str, Sequence[str], None] = 'f97fb85ac765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opportunity_logs_symbol', table_name='opportunity_logs')
    op.drop_index('ix_opportunity_logs_timestamp', table_name='opportunity_logs')
    op.drop_table('opportunity_logs')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.create_table('opportunity_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filter_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filter_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('threshold_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='opportunity_logs_pkey')
    )
    op.create_index('ix_opportunity_logs_timestamp', 'opportunity_logs', ['timestamp'], unique=False)
    op.create_index('ix_opportunity_logs_symbol', 'opportunity_logs', ['symbol'], unique=False)
    # ### end Alembic commands ###
