"""restore_underlying_contract_symbol_to_open_interest

Revision ID: 4c977a060125
Revises: 8acfde31091d
Create Date: 2026-03-06 12:06:57.565423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c977a060125"
down_revision = "8acfde31091d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("open_interest", sa.Column("underlying_contract_symbol", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("open_interest", "underlying_contract_symbol")
    # ### end Alembic commands ###
