"""create rebalance_history table

Revision ID: 50c62e327c2f
Revises: 40daabab1773
Create Date: 2026-03-19 06:40:23.591364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50c62e327c2f'
down_revision = '40daabab1773'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebalance_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('previous_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('applied_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rebalance_history_created_at'), 'rebalance_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebalance_history_created_at'), table_name='rebalance_history')
    op.drop_table('rebalance_history')
    # ### end Alembic commands ###
