"""add_institutional_gaps_fields_v2

Revision ID: 57665afaaacc
Revises: e90c7534c858
Create Date: 2026-03-18 04:20:34.911170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57665afaaacc'
down_revision = 'e90c7534c858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('is_shadow', sa.Boolean(), nullable=True, comment='If true, signals are not sent to the broker'))
    op.add_column('strategies', sa.Column('is_shadow', sa.Boolean(), nullable=True, comment='If true, signals are processed fully but not sent to the broker'))
    op.add_column('trades', sa.Column('signal_timestamp_ns', sa.Numeric(precision=20, scale=0), nullable=True, comment='Nanosecond precision timestamp for latency tracking'))
    op.add_column('trades', sa.Column('latency_ms', sa.Numeric(precision=10, scale=4), nullable=True, comment='Execution latency in milliseconds (Fill - Signal)'))
    op.add_column('trades', sa.Column('is_live', sa.Boolean(), nullable=True))
    op.add_column('trades', sa.Column('is_shadow', sa.Boolean(), nullable=True, comment='If true, signals are not sent to the broker'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_shadow')
    op.drop_column('trades', 'is_live')
    op.drop_column('trades', 'latency_ms')
    op.drop_column('trades', 'signal_timestamp_ns')
    op.drop_column('strategies', 'is_shadow')
    op.drop_column('deployments', 'is_shadow')
    # ### end Alembic commands ###
