"""update_trade_broker_id_lengths

Revision ID: 59cdfb687038
Revises: 4c977a060125
Create Date: 2026-03-06 12:35:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "59cdfb687038"
down_revision = "4c977a060125"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trades", "broker_trade_id", type_=sa.String(length=100))
    op.alter_column("trades", "broker_deal_id", type_=sa.String(length=100))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("trades", "broker_trade_id", type_=sa.String(length=50))
    op.alter_column("trades", "broker_deal_id", type_=sa.String(length=50))
    # ### end Alembic commands ###
