"""institutional_v2_1_sync_fix

Revision ID: 609af3ca29e6
Revises: 8fc4c1af98b6
Create Date: 2026-03-27 01:15:37.084519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609af3ca29e6'
down_revision = '8fc4c1af98b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'broker_deal_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Stable deal identifier for cTrader deduplication; optional for OANDA',
               existing_nullable=True)
    op.drop_constraint(op.f('trades_broker_deal_id_key'), 'trades', type_='unique')
    op.create_index(op.f('ix_trades_broker_deal_id'), 'trades', ['broker_deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_broker_deal_id'), table_name='trades')
    op.create_unique_constraint(op.f('trades_broker_deal_id_key'), 'trades', ['broker_deal_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('trades', 'broker_deal_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Stable deal identifier for cTrader deduplication; optional for OANDA',
               existing_nullable=True)
    # ### end Alembic commands ###
