"""consolidate_schema_and_fix_drifts

Revision ID: 6772ce98e149
Revises: 32966e01de9c
Create Date: 2026-03-03 01:43:59.836441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6772ce98e149'
down_revision: Union[str, Sequence[str], None] = '32966e01de9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='User-defined alias',
               existing_comment='Provider name (e.g., OANDA, BINANCE)',
               existing_nullable=False)
    op.alter_column('data_sources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment='Provider Implementation (e.g., OANDA, BINANCE)',
               existing_nullable=True)
    op.alter_column('funds', 'risk_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.drop_constraint('mental_states_journal_entry_id_fkey', 'mental_states', type_='foreignkey')
    op.create_foreign_key(None, 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    # Drop default before casting to avoid DatatypeMismatch
    op.execute('ALTER TABLE open_interest ALTER COLUMN id DROP DEFAULT')
    op.alter_column('open_interest', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::text::uuid')
    op.drop_constraint('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sentiment_scores', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=4),
               comment='Sentiment score (-1.0 to 1.0)',
               existing_nullable=False)
    op.alter_column('sentiment_scores', 'source_breakdown',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='Sentiment source contributions',
               existing_nullable=True)
    op.drop_index('ix_sentiment_scores_id', table_name='sentiment_scores')
    op.create_index(op.f('ix_sentiment_scores_created_at'), 'sentiment_scores', ['created_at'], unique=False)
    op.drop_constraint('timeline_events_journal_entry_id_fkey', 'timeline_events', type_='foreignkey')
    op.create_foreign_key(None, 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Trading commission in USD',
               existing_nullable=True)
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    op.alter_column('trades', 'commission',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Trading commission in USD',
               existing_nullable=True)
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.create_foreign_key('timeline_events_journal_entry_id_fkey', 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'])
    op.create_index('ix_sentiment_scores_id', 'sentiment_scores', ['id'], unique=False)
    op.alter_column('sentiment_scores', 'source_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Sentiment source contributions',
               existing_nullable=True)
    op.alter_column('sentiment_scores', 'score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sentiment score (-1.0 to 1.0)',
               existing_nullable=False)
    op.drop_constraint(None, 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'])
    op.add_column('open_interest', sa.Column('open_interest', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('open_interest', sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('change_in_oi', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('open_interest', sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint('uq_open_interest_contract_strike_snapshot', 'open_interest', type_='unique')
    op.drop_index('ix_open_interest_snapshot_at_symbol', table_name='open_interest')
    op.drop_index('ix_open_interest_snapshot_at', table_name='open_interest')
    op.drop_index('ix_open_interest_dte', table_name='open_interest')
    op.drop_index('ix_open_interest_contract_symbol', table_name='open_interest')
    op.alter_column('open_interest', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('open_interest', 'put_oi')
    op.drop_column('open_interest', 'call_oi')
    op.drop_column('open_interest', 'strike')
    op.drop_column('open_interest', 'dte')
    op.drop_column('open_interest', 'contract_symbol')
    op.drop_column('open_interest', 'snapshot_at')
    op.drop_constraint(None, 'mental_states', type_='foreignkey')
    op.create_foreign_key('mental_states_journal_entry_id_fkey', 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint('market_categories_name_key', 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('funds', 'risk_percentage',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('data_sources', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Provider Implementation (e.g., OANDA, BINANCE)',
               existing_nullable=True)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='Provider name (e.g., OANDA, BINANCE)',
               existing_comment='User-defined alias',
               existing_nullable=False)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
