"""institutional_history_hardening

Revision ID: 69582d9c23d5
Revises: 609af3ca29e6
Create Date: 2026-03-27 04:45:23.467879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69582d9c23d5'
down_revision = '609af3ca29e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_mortems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('execution_quality', sa.Text(), nullable=True),
    sa.Column('psychological_analysis', sa.Text(), nullable=True),
    sa.Column('alpha_lesson', sa.Text(), nullable=True),
    sa.Column('slippage_pips', sa.Float(), nullable=True),
    sa.Column('execution_latency_ms', sa.Float(), nullable=True),
    sa.Column('profit_efficiency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.trade_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_mortems_trade_id'), 'post_mortems', ['trade_id'], unique=True)
    op.add_column('trades', sa.Column('execution_latency_ms', sa.Numeric(precision=10, scale=4), nullable=True, comment='Execution latency in milliseconds (Broker Fill - System Signal)'))
    op.add_column('trades', sa.Column('slippage_pips', sa.Numeric(precision=10, scale=2), nullable=True, comment='Slippage in pips (Actual Entry - Planned Entry)'))
    op.add_column('trades', sa.Column('slippage_ms', sa.Numeric(precision=10, scale=4), nullable=True, comment='Broker execution latency (Broker Fill - Broker Order)'))
    op.add_column('trades', sa.Column('broker_raw_pnl', sa.Numeric(precision=18, scale=2), nullable=True, comment='Original PnL reported by broker'))
    op.add_column('trades', sa.Column('broker_commission', sa.Numeric(precision=18, scale=2), nullable=True, comment='Original commission reported by broker'))
    op.add_column('trades', sa.Column('broker_swap', sa.Numeric(precision=18, scale=2), nullable=True, comment='Original swap reported by broker'))
    op.add_column('trades', sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful broker reconciliation'))
    op.add_column('trades', sa.Column('reconciliation_status', sa.String(length=20), nullable=True, comment='PENDING, SUCCESS, FAILED'))
    op.drop_column('trades', 'latency_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('latency_ms', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='Execution latency in milliseconds (Fill - Signal)'))
    op.drop_column('trades', 'reconciliation_status')
    op.drop_column('trades', 'reconciled_at')
    op.drop_column('trades', 'broker_swap')
    op.drop_column('trades', 'broker_commission')
    op.drop_column('trades', 'broker_raw_pnl')
    op.drop_column('trades', 'slippage_ms')
    op.drop_column('trades', 'slippage_pips')
    op.drop_column('trades', 'execution_latency_ms')
    op.drop_index(op.f('ix_post_mortems_trade_id'), table_name='post_mortems')
    op.drop_table('post_mortems')
    # ### end Alembic commands ###
