"""Add environment to broker_account

Revision ID: 6ad9d746439e
Revises: ebd0d97d509e
Create Date: 2026-01-19 09:10:42.676930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad9d746439e'
down_revision: Union[str, Sequence[str], None] = 'ebd0d97d509e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('environment', sa.String(length=20), nullable=False, server_default=sa.text("'PRACTICE'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'environment')
    # ### end Alembic commands ###
