"""Add latency and shadow fields to trades

Revision ID: 713a878258ba
Revises: ebd770191395
Create Date: 2026-03-18 14:57:15.562535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713a878258ba'
down_revision = 'ebd770191395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'signal_timestamp_ns',
               existing_type=sa.NUMERIC(precision=20, scale=0),
               type_=sa.BigInteger(),
               existing_comment='Nanosecond precision timestamp for latency tracking',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'signal_timestamp_ns',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=20, scale=0),
               existing_comment='Nanosecond precision timestamp for latency tracking',
               existing_nullable=True)
    # ### end Alembic commands ###
