"""Add performance indexes to open_interest table

Revision ID: 8e17d8f517c8
Revises: 265fd79f8b7d
Create Date: 2026-02-22 03:34:18.911451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e17d8f517c8'
down_revision: Union[str, Sequence[str], None] = '265fd79f8b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('essential_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_execution_logs_deployment_id'), 'strategy_execution_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_logs_timestamp'), 'strategy_execution_logs', ['timestamp'], unique=False)
    op.create_index('ix_open_interest_dte', 'open_interest', ['dte'], unique=False)
    op.create_index('ix_open_interest_snapshot_at_symbol', 'open_interest', ['snapshot_at', 'contract_symbol'], unique=False)
    op.drop_column('open_interest', 'underlying_price')
    # op.alter_column('telegram_chat_mappings', 'user_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # op.create_index(op.f('ix_telegram_chat_mappings_user_id'), 'telegram_chat_mappings', ['user_id'], unique=False)
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'telegram_bot_token',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Encrypted Telegram bot token for user's personal bot",
               existing_nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_chat_mappings', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('open_interest', sa.Column('underlying_price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.drop_index('ix_open_interest_snapshot_at_symbol', table_name='open_interest')
    op.drop_index('ix_open_interest_dte', table_name='open_interest')
    op.drop_index(op.f('ix_strategy_execution_logs_timestamp'), table_name='strategy_execution_logs')
    op.drop_index(op.f('ix_strategy_execution_logs_deployment_id'), table_name='strategy_execution_logs')
    op.drop_table('strategy_execution_logs')
    # ### end Alembic commands ###
