"""institutional_v2_1_sync

Revision ID: 8fc4c1af98b6
Revises: bf981552b4e2
Create Date: 2026-03-27 01:13:55.266568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc4c1af98b6'
down_revision = 'bf981552b4e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
