"""add_account_metadata_fields

Revision ID: 915b7cba0b4d
Revises: 0f4b4407368d
Create Date: 2026-03-17 01:09:59.775330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915b7cba0b4d'
down_revision = '0f4b4407368d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('leverage', sa.Integer(), nullable=True))
    op.add_column('broker_accounts', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('broker_accounts', sa.Column('balance_snapshot', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_accounts', 'balance_snapshot')
    op.drop_column('broker_accounts', 'currency')
    op.drop_column('broker_accounts', 'leverage')
    # ### end Alembic commands ###
