"""authoritative_schema_sync

Revision ID: 9541dec11a94
Revises: cbe66db8debf
Create Date: 2026-03-07 06:18:36.280499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9541dec11a94'
down_revision = 'cbe66db8debf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_component'), table_name='decision_logs')
    op.drop_table('decision_logs')
    op.alter_column('broker_accounts', 'account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'PRACTICE'::character varying"))
    op.create_foreign_key(None, 'broker_accounts', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broker_accounts', type_='foreignkey')
    op.alter_column('broker_accounts', 'environment',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'PRACTICE'::character varying"))
    op.alter_column('broker_accounts', 'account_number',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table('decision_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('component', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tool_call', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outcome', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_logs_pkey'))
    )
    op.create_index(op.f('ix_decision_logs_component'), 'decision_logs', ['component'], unique=False)
    # ### end Alembic commands ###
