"""fix_schema_drift_comments_and_nullability

Revision ID: 9c0e4b93a140
Revises: 0c2a22f5bd76
Create Date: 2026-03-23 05:39:24.685785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0e4b93a140'
down_revision = '0c2a22f5bd76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
