"""add_parent_trade_id

Revision ID: a091b34fd111
Revises: f1490272dc39
Create Date: 2026-03-24 20:00:17.159961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091b34fd111'
down_revision = 'f1490272dc39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('parent_trade_id', sa.UUID(), nullable=True, comment='For child trades (TWAP/VWAP/Partial Close)'))
    op.create_index(op.f('ix_trades_parent_trade_id'), 'trades', ['parent_trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_parent_trade_id'), table_name='trades')
    op.drop_column('trades', 'parent_trade_id')
    # ### end Alembic commands ###
