"""Add professional api key fields

Revision ID: a7bdb78d0b74
Revises: 5ee6ebb334fb
Create Date: 2026-04-05 04:49:42.244687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7bdb78d0b74'
down_revision = '5ee6ebb334fb'
branch_labels = None
depends_on = None


def upgrade() -> sa.Enum:
    # Create the enum type first
    apikeyrole = sa.Enum('OWNER', 'MANAGER', 'TRADER', 'VIEWER', name='apikeyrole')
    apikeyrole.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('fund_id', sa.UUID(), nullable=True))
    
    # Add role as nullable first to handle existing rows
    op.add_column('api_keys', sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'TRADER', 'VIEWER', name='apikeyrole'), nullable=True))
    
    # Update existing rows to a default role (e.g., OWNER for existing keys, or VIEWER for safety)
    # Since these are existing keys, we'll assume OWNER or look them up. 
    # For now, let's set to OWNER to avoid breaking existing users.
    op.execute("UPDATE api_keys SET role = 'OWNER' WHERE role IS NULL")
    
    # Now set it to NOT NULL
    op.alter_column('api_keys', 'role', nullable=False)
    
    op.add_column('api_keys', sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='["*"]', nullable=False))
    op.add_column('api_keys', sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('rate_limit_rpm', sa.Integer(), server_default='60', nullable=False))
    op.create_foreign_key(None, 'api_keys', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> sa.Enum:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'rate_limit_rpm')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'allowed_ips')
    op.drop_column('api_keys', 'scopes')
    op.drop_column('api_keys', 'role')
    op.drop_column('api_keys', 'fund_id')
    # ### end Alembic commands ###

    # Drop the enum type
    apikeyrole = sa.Enum('OWNER', 'MANAGER', 'TRADER', 'VIEWER', name='apikeyrole')
    apikeyrole.drop(op.get_bind(), checkfirst=True)


