"""add_strategy_id_to_signal_log

Revision ID: ac4ccbc94864
Revises: 2769a2d00d26
Create Date: 2026-03-02 11:19:28.165799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac4ccbc94864'
down_revision: Union[str, Sequence[str], None] = '2769a2d00d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_logs', sa.Column('strategy_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_signal_logs_strategy_id'), 'signal_logs', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
