"""add_strategy_id_to_signal_log

Revision ID: ac4ccbc94864
Revises: 2769a2d00d26
Create Date: 2026-03-02 11:19:28.165799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac4ccbc94864'
down_revision: Union[str, Sequence[str], None] = '2769a2d00d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_economic_events_datetime', table_name='economic_events')
    op.drop_index('ix_economic_events_external_id', table_name='economic_events')
    op.drop_index('ix_economic_events_id', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('ix_cot_records_report_date', table_name='cot_records')
    op.drop_index('ix_cot_records_symbol', table_name='cot_records')
    op.drop_table('cot_records')
    op.drop_table('alembic_version_pipeline')
    op.drop_index('ix_news_articles_external_id', table_name='news_articles')
    op.drop_index('ix_news_articles_id', table_name='news_articles')
    op.drop_index('ix_news_articles_published_at', table_name='news_articles')
    op.drop_index('ix_news_articles_symbol', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.drop_constraint('market_categories_name_key', 'market_categories', type_='unique')
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    op.drop_constraint('mental_states_journal_entry_id_fkey', 'mental_states', type_='foreignkey')
    op.create_foreign_key(None, 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_column('open_interest', 'underlying_contract_symbol')
    op.drop_constraint('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.add_column('signal_logs', sa.Column('strategy_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_signal_logs_strategy_id'), 'signal_logs', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    op.drop_constraint('timeline_events_journal_entry_id_fkey', 'timeline_events', type_='foreignkey')
    op.create_foreign_key(None, 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_trades_broker_trade_id', table_name='trades')
    op.drop_constraint('trades_broker_deal_id_key', 'trades', type_='unique')
    op.drop_column('trades', 'gross_pnl')
    op.drop_column('trades', 'broker_deal_id')
    op.drop_column('trades', 'broker_trade_id')
    op.drop_column('trades', 'swap')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('swap', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('broker_trade_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('broker_deal_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('gross_pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_unique_constraint('trades_broker_deal_id_key', 'trades', ['broker_deal_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_trades_broker_trade_id', 'trades', ['broker_trade_id'], unique=False)
    op.drop_constraint(None, 'timeline_events', type_='foreignkey')
    op.create_foreign_key('timeline_events_journal_entry_id_fkey', 'timeline_events', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.drop_index(op.f('ix_signal_logs_strategy_id'), table_name='signal_logs')
    op.drop_column('signal_logs', 'strategy_id')
    op.drop_constraint(None, 'root_cause_analyses', type_='foreignkey')
    op.create_foreign_key('root_cause_analyses_journal_entry_id_fkey', 'root_cause_analyses', 'journal_entries', ['journal_entry_id'], ['id'])
    op.add_column('open_interest', sa.Column('underlying_contract_symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mental_states', type_='foreignkey')
    op.create_foreign_key('mental_states_journal_entry_id_fkey', 'mental_states', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint('market_categories_name_key', 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.create_table('news_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_articles_pkey')
    )
    op.create_index('ix_news_articles_symbol', 'news_articles', ['symbol'], unique=False)
    op.create_index('ix_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_id', 'news_articles', ['id'], unique=False)
    op.create_index('ix_news_articles_external_id', 'news_articles', ['external_id'], unique=True)
    op.create_table('alembic_version_pipeline',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pipeline_pkc')
    )
    op.create_table('cot_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('commercials_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('commercials_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_commercials_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('non_commercials_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False),
    sa.Column('managed_money_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('managed_money_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('non_reportable_long', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('non_reportable_short', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cot_records_pkey'),
    sa.UniqueConstraint('symbol', 'report_date', name='uq_cot_records_symbol_report_date', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_cot_records_symbol', 'cot_records', ['symbol'], unique=False)
    op.create_index('ix_cot_records_report_date', 'cot_records', ['report_date'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('impact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('actual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('forecast', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('previous', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='economic_events_pkey')
    )
    op.create_index('ix_economic_events_id', 'economic_events', ['id'], unique=False)
    op.create_index('ix_economic_events_external_id', 'economic_events', ['external_id'], unique=True)
    op.create_index('ix_economic_events_datetime', 'economic_events', ['datetime'], unique=False)
    # ### end Alembic commands ###
