"""final_institutional_sync_v2

Revision ID: ad3b92fa74c7
Revises: ba82c939943c
Create Date: 2026-03-19 00:34:31.249392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3b92fa74c7'
down_revision = 'ba82c939943c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('deployments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_deployments_fund_id'), table_name='deployments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deployments_fund_id'), 'deployments', ['fund_id'], unique=False)
    op.drop_column('deployments', 'created_at')
    op.drop_column('deployments', 'is_active')
    # ### end Alembic commands ###
