"""init_pipeline_schema_fixed_v2

Revision ID: afae1460db4d
Revises: 
Create Date: 2026-01-13 09:58:15.291193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afae1460db4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_market_categories_name', table_name='market_categories')
    op.create_unique_constraint(None, 'market_categories', ['name'])
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('market_symbols', 'details') 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('market_symbols', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    op.drop_constraint(None, 'market_categories', type_='unique')
    op.create_index('ix_market_categories_name', 'market_categories', ['name'], unique=True)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    # ### end Alembic commands ###
