"""verify_drift

Revision ID: ba1c9ebbb8f5
Revises: 08df85ab00a2
Create Date: 2026-03-30 10:43:41.389108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1c9ebbb8f5'
down_revision = '08df85ab00a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_mortems', 'pnl_net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               comment='Net profit after fees and slippage',
               existing_nullable=True)
    op.alter_column('post_mortems', 'smart_score',
               existing_type=sa.INTEGER(),
               comment='Proprietary AI score for trade quality (0-100)',
               existing_nullable=True)
    op.alter_column('trades', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner of the trade (RBAC)',
               existing_nullable=True)
    op.alter_column('trades', 'fund_id',
               existing_type=sa.UUID(),
               comment='Fund that the trade belongs to (RBAC)',
               existing_nullable=True)
    op.alter_column('trades', 'latency_ms',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Total systemic latency (Signal -> Execution Fill)',
               existing_nullable=True)
    op.create_index(op.f('ix_trades_fund_id'), 'trades', ['fund_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_foreign_key(None, 'trades', 'funds', ['fund_id'], ['id'])
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_fund_id'), table_name='trades')
    op.alter_column('trades', 'latency_ms',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Total systemic latency (Signal -> Execution Fill)',
               existing_nullable=True)
    op.alter_column('trades', 'fund_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Fund that the trade belongs to (RBAC)',
               existing_nullable=True)
    op.alter_column('trades', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner of the trade (RBAC)',
               existing_nullable=True)
    op.alter_column('post_mortems', 'smart_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Proprietary AI score for trade quality (0-100)',
               existing_nullable=True)
    op.alter_column('post_mortems', 'pnl_net',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Net profit after fees and slippage',
               existing_nullable=True)
    # ### end Alembic commands ###
