"""add_account_history_and_risk_parity_fields

Revision ID: ba82c939943c
Revises: 713a878258ba
Create Date: 2026-03-19 00:26:02.310480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba82c939943c'
down_revision = '713a878258ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type explicitly
    risk_parity_model_enum = sa.Enum('MIN_VOL', 'HRP', 'ERC', name='risk_parity_model_enum')
    risk_parity_model_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('account_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('used_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unrealized_gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unrealized_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_history_broker_account_id'), 'account_history', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_account_history_timestamp'), 'account_history', ['timestamp'], unique=False)
    op.add_column('funds', sa.Column('risk_parity_enabled', sa.Boolean(), nullable=True))
    op.add_column('funds', sa.Column('risk_parity_model', sa.Enum('MIN_VOL', 'HRP', 'ERC', name='risk_parity_model_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'risk_parity_model')
    op.drop_column('funds', 'risk_parity_enabled')
    op.drop_index(op.f('ix_account_history_timestamp'), table_name='account_history')
    op.drop_index(op.f('ix_account_history_broker_account_id'), table_name='account_history')
    op.drop_table('account_history')
    
    # Drop enum type explicitly
    sa.Enum('MIN_VOL', 'HRP', 'ERC', name='risk_parity_model_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
