"""Add EconomicEvent model

Revision ID: bac00dc3e45d
Revises: 297d759e01ee
Create Date: 2026-02-08 01:03:55.665081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bac00dc3e45d'
down_revision = '297d759e01ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual', sa.String(), nullable=True),
    sa.Column('forecast', sa.String(), nullable=True),
    sa.Column('previous', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_events_datetime'), 'economic_events', ['datetime'], unique=False)
    op.create_index(op.f('ix_economic_events_external_id'), 'economic_events', ['external_id'], unique=True)
    op.create_index(op.f('ix_economic_events_id'), 'economic_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_economic_events_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_external_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_datetime'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
