"""add_execution_algo_to_trades

Revision ID: bf981552b4e2
Revises: a091b34fd111
Create Date: 2026-03-24 20:18:46.647651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf981552b4e2'
down_revision = 'a091b34fd111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('execution_algo', sa.String(length=50), nullable=True, comment='Execution algorithm used (TWAP, VWAP, SCALE_IN)'))
    op.add_column('trades', sa.Column('algo_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Parameters for the execution algorithm'))
    op.add_column('trades', sa.Column('algo_status', sa.String(length=20), nullable=True, comment='Status of the execution algorithm'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'algo_status')
    op.drop_column('trades', 'algo_params')
    op.drop_column('trades', 'execution_algo')
    # ### end Alembic commands ###
