"""add_ai_labels_to_candles

Revision ID: c1b94a3f0277
Revises: 448e5a59cf50
Create Date: 2026-03-22 04:15:53.887904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1b94a3f0277'
down_revision = '448e5a59cf50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('ai_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Automated labels (e.g., fake_sweep, expansion_confirmed)'))
    op.add_column('candles', sa.Column('regime_tag', sa.String(length=50), nullable=True, comment='Market regime classification'))
    op.alter_column('signal_logs', 'knowledge_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('trades', 'knowledge_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='GraphRAG context snapshot from FalkorDB',
               existing_nullable=True)
    op.alter_column('trades', 'knowledge_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=4),
               comment='Semantic confidence score (0.0 to 1.5)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'knowledge_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=3, scale=2),
               comment=None,
               existing_comment='Semantic confidence score (0.0 to 1.5)',
               existing_nullable=True)
    op.alter_column('trades', 'knowledge_context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='GraphRAG context snapshot from FalkorDB',
               existing_nullable=True)
    op.alter_column('signal_logs', 'knowledge_score',
               existing_type=sa.Numeric(precision=5, scale=4),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.drop_column('candles', 'regime_tag')
    op.drop_column('candles', 'ai_labels')
    # ### end Alembic commands ###
