"""add_auto_protect_fields

Revision ID: c1feb0128bf8
Revises: 35208bf0cf57
Create Date: 2026-03-20 21:11:45.530018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1feb0128bf8'
down_revision = '35208bf0cf57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('auto_protect_enabled', sa.Boolean(), nullable=False))
    op.add_column('funds', sa.Column('emergency_sl_pips', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'emergency_sl_pips')
    op.drop_column('funds', 'auto_protect_enabled')
    # ### end Alembic commands ###
