"""add_oi_greek_fields_final

Revision ID: c6fc08dced5a
Revises: a7bdb78d0b74
Create Date: 2026-04-20 07:17:35.863032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6fc08dced5a'
down_revision = 'a7bdb78d0b74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Institutional Greek Fields (Idempotent Addition)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('open_interest')]
    
    greeks = [
        ('implied_volatility', sa.Numeric(precision=18, scale=8), "Synthetic or derived Implied Volatility (GVZ baseline + Skew)"),
        ('delta', sa.Numeric(precision=18, scale=8), None),
        ('gamma', sa.Numeric(precision=18, scale=8), None),
        ('vega', sa.Numeric(precision=18, scale=8), None),
        ('theta', sa.Numeric(precision=18, scale=8), None),
        ('vanna', sa.Numeric(precision=18, scale=8), "Sensitivity of Option Delta to changes in IV (dDelta/dVol)"),
        ('charm', sa.Numeric(precision=18, scale=8), "Rate of Change of Option Delta over time (Delta Decay)")
    ]
    
    for col_name, col_type, col_comment in greeks:
        if col_name not in columns:
            op.add_column('open_interest', sa.Column(col_name, col_type, nullable=True, comment=col_comment))

    # Clean up obsolete tables
    if inspector.has_table('liquidity_metrics'):
        # Only drop if truly obsolete (institutional standard)
        op.drop_table('liquidity_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidity_metrics',
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_liquidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('correlation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('z_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('squeeze_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_correlation_1_0', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_price_undervalued', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
