"""final_schema_sync

Revision ID: cbe66db8debf
Revises: 30ae3ae23514
Create Date: 2026-03-07 03:01:52.776103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbe66db8debf'
down_revision = '30ae3ae23514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.add_column('candles', sa.Column('market_symbol_id', sa.UUID(), nullable=False, comment='Foreign Key to MarketSymbol (defines Symbol + DataSource)'))
    op.add_column('candles', sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible storage for calculated indicators (RSI, EMA, etc.)'))
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(),
               comment='Denormalized symbol for easier querying (e.g. XAUUSD)',
               existing_comment='Trading pair symbol (e.g., XAU/USD)',
               existing_nullable=False)
    op.drop_index(op.f('ix_candles_symbol_timeframe_timestamp'), table_name='candles')
    op.create_index('ix_candles_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_market_symbol_id'), 'candles', ['market_symbol_id'], unique=False)
    op.create_index('ix_candles_market_symbol_timeframe_timestamp', 'candles', ['market_symbol_id', 'timeframe', 'timestamp'], unique=True)
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.add_column('data_sources', sa.Column('provider', sa.String(), nullable=True, comment='Provider Implementation (e.g., OANDA, BINANCE)'))
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='User-defined alias',
               existing_comment='Provider name (e.g., OANDA, BINANCE)',
               existing_nullable=False)
    op.alter_column('deployments', 'config_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('deployments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               nullable=False,
               postgresql_using='status::deployment_status_enum')
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_strategy_id'), 'deployments', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_deployments_user_id'), 'deployments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'deployments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'deployments', 'saved_strategies', ['strategy_id'], ['id'], ondelete='CASCADE')
    op.add_column('saved_strategies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('saved_strategies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('saved_strategies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('saved_strategies', 'last_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Persisted backtest metrics and plot',
               existing_nullable=True)
    op.create_foreign_key(None, 'saved_strategies', 'users', ['user_id'], ['id'])
    op.add_column('signal_logs', sa.Column('strategy_id', sa.UUID(), nullable=True))
    op.alter_column('signal_logs', 'execution_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='execution_id::uuid')
    op.alter_column('signal_logs', 'sentiment_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_signal_logs_strategy_id'), 'signal_logs', ['strategy_id'], unique=False)
    op.create_foreign_key(None, 'signal_logs', 'strategies', ['strategy_id'], ['id'])
    op.create_foreign_key(None, 'signal_logs', 'deployments', ['deployment_id'], ['id'])
    op.add_column('strategies', sa.Column('config_id', sa.UUID(), nullable=True))
    op.alter_column('strategies', 'template_id',
               existing_type=sa.VARCHAR(),
               comment="Identifier for the strategy logic template (e.g., 'SMC_V1')",
               existing_nullable=False)
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_nullable=False)
    op.create_foreign_key(None, 'strategies', 'strategy_configs', ['config_id'], ['id'])
    op.create_foreign_key(None, 'strategies', 'broker_accounts', ['broker_account_id'], ['id'])
    op.create_foreign_key(None, 'strategies', 'funds', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.alter_column('strategies', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Strategy-specific configuration parameters (overrides template defaults)',
               existing_nullable=False)
    op.alter_column('strategies', 'template_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Identifier for the strategy logic template (e.g., 'SMC_V1')",
               existing_nullable=False)
    op.drop_column('strategies', 'config_id')
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.drop_constraint(None, 'signal_logs', type_='foreignkey')
    op.drop_index(op.f('ix_signal_logs_strategy_id'), table_name='signal_logs')
    op.alter_column('signal_logs', 'sentiment_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('signal_logs', 'execution_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('signal_logs', 'strategy_id')
    op.drop_constraint(None, 'saved_strategies', type_='foreignkey')
    op.alter_column('saved_strategies', 'last_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Persisted backtest metrics and plot',
               existing_nullable=True)
    op.drop_column('saved_strategies', 'updated_at')
    op.drop_column('saved_strategies', 'created_at')
    op.drop_column('saved_strategies', 'description')
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_index(op.f('ix_deployments_user_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_strategy_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.alter_column('deployments', 'status',
               existing_type=sa.Enum('STARTING', 'ACTIVE', 'STOPPED', 'ERROR', 'STOPPING', name='deployment_status_enum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('deployments', 'config_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(),
               comment='Provider name (e.g., OANDA, BINANCE)',
               existing_comment='User-defined alias',
               existing_nullable=False)
    op.drop_column('data_sources', 'provider')
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.drop_index('ix_candles_market_symbol_timeframe_timestamp', table_name='candles')
    op.drop_index(op.f('ix_candles_market_symbol_id'), table_name='candles')
    op.drop_index('ix_candles_symbol_timeframe_timestamp', table_name='candles')
    op.create_index(op.f('ix_candles_symbol_timeframe_timestamp'), 'candles', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.alter_column('candles', 'symbol',
               existing_type=sa.VARCHAR(),
               comment='Trading pair symbol (e.g., XAU/USD)',
               existing_comment='Denormalized symbol for easier querying (e.g. XAUUSD)',
               existing_nullable=False)
    op.drop_column('candles', 'indicators')
    op.drop_column('candles', 'market_symbol_id')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
