"""Add Phase 9 Knowledge fields

Revision ID: d0b9ff2f6dac
Revises: 2845c0a22860
Create Date: 2026-03-21 06:13:46.866878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b9ff2f6dac'
down_revision = '2845c0a22860'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
