"""add details to market_symbols

Revision ID: e09819f1be5d
Revises: 617e8fa4eb75
Create Date: 2026-01-04 10:01:06.075321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e09819f1be5d'
down_revision: Union[str, Sequence[str], None] = '617e8fa4eb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_symbols', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_symbols', 'details')
    # ### end Alembic commands ###
