"""add_pm_classification_fixed

Revision ID: e1e3daed55a5
Revises: f56ba7438dc1
Create Date: 2026-03-27 05:11:31.024635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1e3daed55a5'
down_revision = 'f56ba7438dc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_mortems', sa.Column('classification', sa.String(length=50), nullable=True, comment='GOOD_WIN, BAD_WIN, GOOD_LOSS, BAD_LOSS'))
    op.alter_column('post_mortems', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('post_mortems', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_mortems', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('post_mortems', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('post_mortems', 'classification')
    # ### end Alembic commands ###
