"""add_data_source_id_to_broker_accounts

Revision ID: e90c7534c858
Revises: 915b7cba0b4d
Create Date: 2026-03-17 01:49:30.880300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90c7534c858'
down_revision = '915b7cba0b4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('data_source_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'broker_accounts', 'data_sources', ['data_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broker_accounts', type_='foreignkey')
    op.drop_column('broker_accounts', 'data_source_id')
    # ### end Alembic commands ###
