"""add_signal_log_status

Revision ID: ebd0d97d509e
Revises: 24660acd5860
Create Date: 2026-01-17 13:03:30.045528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd0d97d509e'
down_revision: Union[str, Sequence[str], None] = '24660acd5860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    op.add_column('signal_logs', sa.Column('execution_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_logs', 'execution_id')
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
