"""add_signal_log_status

Revision ID: ebd0d97d509e
Revises: 24660acd5860
Create Date: 2026-01-17 13:03:30.045528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd0d97d509e'
down_revision: Union[str, Sequence[str], None] = '24660acd5860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_pipeline')
    op.drop_constraint('candles_market_symbol_id_fkey', 'candles', type_='foreignkey')
    op.create_foreign_key(None, 'candles', 'market_symbols', ['market_symbol_id'], ['id'])
    op.drop_constraint('market_categories_name_key', 'market_categories', type_='unique')
    op.create_index(op.f('ix_market_categories_name'), 'market_categories', ['name'], unique=True)
    op.drop_constraint('market_symbols_data_source_id_fkey', 'market_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'market_symbols', 'data_sources', ['data_source_id'], ['id'])
    op.add_column('signal_logs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('signal_logs', sa.Column('execution_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_logs', 'execution_id')
    op.drop_column('signal_logs', 'status')
    op.drop_constraint(None, 'market_symbols', type_='foreignkey')
    op.create_foreign_key('market_symbols_data_source_id_fkey', 'market_symbols', 'data_sources', ['data_source_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_market_categories_name'), table_name='market_categories')
    op.create_unique_constraint('market_categories_name_key', 'market_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'candles', type_='foreignkey')
    op.create_foreign_key('candles_market_symbol_id_fkey', 'candles', 'market_symbols', ['market_symbol_id'], ['id'], ondelete='CASCADE')
    op.create_table('alembic_version_pipeline',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pipeline_pkc')
    )
    # ### end Alembic commands ###
