"""add_signal_id_to_trades

Revision ID: ebd770191395
Revises: 57665afaaacc
Create Date: 2026-03-18 07:45:17.382826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd770191395'
down_revision = '57665afaaacc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('signal_id', sa.UUID(), nullable=True, comment='Link to the specific signal that triggered this trade'))
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_column('trades', 'signal_id')
    # ### end Alembic commands ###
