"""increase_candle_volume_precision

Revision ID: f1490272dc39
Revises: 2263d8e0ed20
Create Date: 2026-03-23 13:16:02.128571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1490272dc39'
down_revision = '2263d8e0ed20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'volume',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_comment='Trading volume',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candles', 'volume',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=8),
               existing_comment='Trading volume',
               existing_nullable=False)
    # ### end Alembic commands ###
