"""institutional_history_v2

Revision ID: f56ba7438dc1
Revises: 69582d9c23d5
Create Date: 2026-03-27 05:05:44.082171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56ba7438dc1'
down_revision = '69582d9c23d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
