"""Add SystemPrompt and AuditLog tables

Revision ID: f97fb85ac765
Revises: 1c634932f29f
Create Date: 2026-01-08 15:52:10.557517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97fb85ac765'
down_revision: Union[str, Sequence[str], None] = '1c634932f29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
