"""add index to rebalance_history fund_id

Revision ID: f98d1ccf91c9
Revises: 50c62e327c2f
Create Date: 2026-03-19 06:43:35.158969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98d1ccf91c9'
down_revision = '50c62e327c2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rebalance_history_fund_id'), 'rebalance_history', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebalance_history_fund_id'), table_name='rebalance_history')
    # ### end Alembic commands ###
